### ISSUE TITLE
Does "random pitch" always lower the pitch?

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1042]
It seems to me that random pitch always lowers the pitch.
Wouldn't a gaussian distribution centered in zero be reasonable for this feature instead?

here is the code in `src/core/hydrogen.cpp`, :
```
			const float fMaxPitchDeviation = 2.0;
			pNote->set_pitch( pNote->get_pitch()
						 + pNote->get_instrument()->get_pitch_offset()
						 + ( fMaxPitchDeviation * getGaussian( 0.2 )
							  - fMaxPitchDeviation / 2.0 )
							  * pNote->get_instrument()->get_random_pitch_factor() );
```
For what I understand:
when `random_pitch_factor`= 1, pitch gets lowered by 1 half step and summed to 2*output of getgaussian() (which is centered in 0, width 0.2)
I would drop   `- fMaxPitchDeviation / 2.0 `.
Am I missing something?

**Comment by theGreatWhiteShark** [comment]
Nice catch!

Seems like there was formerly white noise instead of the Gaussian in place.

But another thing not covered is the truncation since the Gaussian has support from minus to plus infinity. @oddtime since you worked with pitch quite a lot lately: is there a reason or exact value (at the upper and lower end) to truncate the pitch at?

**Comment by oddtime** [comment]
For info these are 100000 calls of `getGaussian( 0.2 )`
![gaussian](https://user-images.githubusercontent.com/54219881/103211878-acf1e780-4909-11eb-8ee4-f99829580b80.png)

**Comment by oddtime** [comment]
> is there a reason or exact value (at the upper and lower end) to truncate the pitch at?
Well I didn't read how the pitch shift works, but probably the limit is so high that we can decide a smaller interval for truncation, like for example the gaussian width * 4, I mean [-0.8; 0.8] in the previous plot

**Comment by theGreatWhiteShark** [comment]
> is there a reason or exact value (at the upper and lower end) to truncate the pitch at?

It's not solely related to the random contribution. We can e.g. have a high-pitched note + maximum offset + random contribution. I'm just not sure whether there are any practical limits we might violate. If there are none, even better and we are already done :)

**Comment by oddtime** [comment]
I had a look at `bool Sampler::renderNoteResample` in file `src/core/Sampler.cpp`, I guess you know it better than me.
I didn't notice explicit limitations arriving there.
But if the random pitch is something like -100 octaves, which is fine for the calculation I think, the result would not be audible (and I don't know if there's a hi pass filter to protect speakers / headphones from signal offset...)
Or if it's something like +100 octaves the length of the resampled discrete signal may be 1 sample long...
maybe.
Truncation of a reasonable number of half steps may be fine

**Comment by theGreatWhiteShark** [comment]
> I guess you know it better than me.

Nope. I'm not asking rhetorical questions to keep you busy :wink: . Hydrogen has a rather large code base and I haven't looked at all parts let alone remember everything I have encountered.

> Also, there's a musical reason to keep random pitch in a small range

Right now - with a standard deviation of 0.2 - there is a probability of lowering the pitch for more than -1 of 2.866516e-07. This seems sufficiently small. Also, this is only for a random pitch knob turned all the way to 1. Since it's value is multiplied with the resulting number and a Gaussian random process scaled by a factor is the same as scaling it's standard deviation, the drawn pitches will be even less in most cases.

But if we ever decide to support other types of noise distributions with heavy tails, we should introduce the truncation.

(I will close the issue with the associated PR. Please feel free to reopen if you think there is something more to be done)

**Comment by oddtime** [comment]
Sure, I thought you wanted add a truncation to be exactly sure that such event will never occur.

**Comment by theGreatWhiteShark** [comment]
> I thought you wanted to add a truncation to be exactly sure that such event will never occur.

I was more concerned about the sampler being unable to handle very high/low pitches not about the distribution (though I did not stated it this way). I was occasionally thinking about this since you introduced the pitch offset but never had time to check in the code. But since it doesn't everything is fine from my point of view.

**Comment by oddtime** [comment]
Ah ok!
Lowering the pitch I guess there is no problem at all, since it is interpolating the digital signal between each contiguous sample. (linearly or with other methods)
I wonder if there's (or if it is necessary) an antialiasing filter before resampling the pitch when raising the pitch...

**Comment by oddtime** [comment]
I didn't consider rubberband pitch shift in my previous comments

**Comment by theGreatWhiteShark** [comment]
> Maybe this could open another issue in a far future :)

Sure.

In the audio engine there are most probably a lot of places improvements can happen. I also intend have a more thorough look. But right now making existing things work (more smoothly) is at higher priority.
