### ISSUE TITLE
Destructive mode recording in pattern editor

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1102]
I just discovered a quite obscure feature:

If you *right click* the record button in the player control another drop down menu appears in the panel of the pattern editor. And if you choose one of the lower options a second drop down appears. It's dubbed "destructive mode pre/post delete settings".

![destructiveRecording](https://user-images.githubusercontent.com/14164547/104806842-b2d93b00-57da-11eb-907a-a1502d3d0c0b.png)

It's a stored in the `Preferences` class but not written to disk. The drop down menus do not integrate into the pattern editor panel nicely. It's hard to discover and not documented.

@mauser @cme Can we remove this?

**Comment by trebmuh** [comment]
Wahou! Never found this one! And I've been wondering for a long time now what this "`destructive mode pre/post delete settings`" string was referring to in the French translation file!

Trying to play a bit with this "hidden" feature:
* I'm noticing that when right-clicking the record button in the player control, the red-dot turns to a red-dot-minus-a-small-part
* I'm not able to understand very well how it is supposed to work, it seems it's adding notes lines over and over again until the sound is distorted and hydrogen start to become laggy

**Comment by theGreatWhiteShark** [comment]
> I'm not able to understand very well how it is supposed to work, it seems it's adding notes lines over and over again until the sound is distorted and hydrogen start to become laggy

I think it's purpose was to remove all notes in close vicinity of the newly recorded one. Well, it's around for 12 years and most probably not kept in sync with changes applied to the pattern editor and the note recording.

**Comment by trebmuh** [comment]
Probably since I didn't success to find a way to remove some dot while playing around with this option. It just keeps adding note again and again.

**Comment by mauser** [comment]
Hi! 

I remember that this was a feature @wolkstein was working on to ease midi recording. IIRC, there has also been discussion about a "Punch in" feature for midi recording at that time, but i'm not sure if that got implemented. I've never used midi recording in Hydrogen at all..

I suppose it wouldn't hurt to remove this, especially if it is currently not working and no one knows how it is supposed to work :man_shrugging: Otherwise we would have to find a better way to integrate it and fix the functionality
