### ISSUE TITLE
old gmkit test.wav?

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1137]
Hi guys
I was tryng to solve a unit test fail and I listened to a file that seems using the old gmkit: `hydrogen/src/tests/data/functional/test.wav`

**Comment by theGreatWhiteShark** [comment]
I will look into it

**Comment by theGreatWhiteShark** [comment]
This was actually a legit fail. 

The new pan calculation yields slightly different results since it's dividing two floats with non-zero content all the way to the last digit and causes some truncation. But this should not be audible because it only introduces changes to the audio output at the 6-8 decimal place.

**Comment by oddtime** [comment]
I assume this is related to #1061.
But what about this file? I removed it and all the tests do pass

**Comment by theGreatWhiteShark** [comment]
> But what about this file? I removed it and all the tests do pass

Okay. Maybe I misunderstood the purpose of this issue. The file is indeed redundant. I removed it in 1722223.

**Comment by oddtime** [comment]
Ok!
