### ISSUE TITLE
i18n issues - 2

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#1207]
Hydrogen version *          : GIT master 4aa5668
Operating system + version  : Debian 10 / LibraZiK 3
Audio driver + version      : JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Following #397 

Here are a few i18n glitches.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

menu -> Drumkits -> Properties

![hydro1](https://user-images.githubusercontent.com/8705846/110690843-ae327100-81e4-11eb-9740-e26293694959.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

menu -> Drumkits -> Online Import

![hydro2](https://user-images.githubusercontent.com/8705846/110691271-3b75c580-81e5-11eb-97fb-95ed5c028144.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Instruments -> Layers -> LOAD LAYERS

![hydro3](https://user-images.githubusercontent.com/8705846/110691612-a7582e00-81e5-11eb-99b4-bda6b88cf061.png)

**Comment by cme** [comment]
Looks like fixed-size layouts that should be fairly easy to convert to responsive QLayout-based dialogs. I've taken a pass at the AudioFileBrowser one already.

**Comment by trebmuh** [comment]
Thank you very much.
I can confirm that all is fine with the French translation (rebuild from aa738c3)
Closing here now.

**Comment by theGreatWhiteShark** [comment]
> Looks like fixed-size layouts that should be fairly easy to convert to responsive QLayout-based dialogs.

@cme can you recommend a resource using which I could introduce myself into the QLayout stuff? I did naively open the `QT Designer` and tried my luck with Online Import one. But those widgets kept jumping around, inserted larger vertical spaces, and did not obey the height/width values I supplied. After two hours I threw in the towel since the Qt Doc was not really helping me either.

**Comment by cme** [comment]
I don't really have anything I'm afraid, other than looking up Qt docs for specific issues. Qt Designer really is incredibly fiddly about placing widgets inside preexisting QLayouts, I think it seems to be single-pixel accuracy needed. I don't know how other people put up with that for anything more than occasional use! I found that rather than trying to insert things into layouts, the better approach (especially for UIs that are currently designed with absolute positioning) is to break existing layouts, then build the new layout bottom-up by selecting multiple widgets, and using the "Lay out" submenu to build a new QLayout around the selected items.

**Comment by theGreatWhiteShark** [comment]
Okay. I see.

> I found that rather than trying to insert things into layouts, the better approach (especially for UIs that are currently designed with absolute positioning) is to break existing layouts, then build the new layout bottom-up by selecting multiple widgets, and using the "Lay out" submenu to build a new QLayout around the selected items.

That thought crossed my mind too. But at that time I considered it an overkill. Well, maybe next time :)
