### ISSUE TITLE
Error messaging when displaying drumkit properties via the Soundlibrary panel

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#1222]
Hydrogen version *          :  Hydrogen 1.1.0-'d7d3db9a'

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hydrogen shows an error message when using the "Properties" dialog of a drumkit via the soundlibrary panel. It does not matter if a user or a system drumkit has been selected.. 

![image](https://user-images.githubusercontent.com/202461/112736237-7bf97100-8f51-11eb-9c48-61ca91b38a02.png)

The dialog prints out "GmRockKit" for each time the dialog has been opened.

**Comment by theGreatWhiteShark** [comment]
That's quite strange and I can not reproduce this. Can you attach the log? Also, could you run `xmllint` on your local version of the GMRockKit?

It seems H2 is unable to find and load your current drumkit. This is required because the other drumkit has to be loaded in order to view/edit its properties. Afterwards, the previous one will be reloaded.

Also, I'm quite puzzled why the drumkit name appears several times in the dialog. It should display the return value of `Hydrogen::getCurrentDrumkitName()`, which is supposed to be a const ref to a QString.

**Comment by mauser** [comment]
Hi, 

i did some more investigation today. Time was a bit short on last saturday for debugging :) 

It seems that there are two issues: 

(1): `SoundLibraryPanel::on_drumkitPropertiesAction()` makes the following call: 
      `QMessageBox::warning( this, "Hydrogen", m_sMessageFailedPreDrumkitLoad.append( QString( " [%1]").arg( PreDrumkitName ) ) );` 
      So this appends directly to the internal member m_sMessageFailedPreDrumkitLoad, which should explain the strange string. 
      
(2): There seems to be a new song property "drumkitLookup". If this is not present in the current song, it is set to Lookup::user. 
       In SoundLibraryPanel Line 762, this lookup is used to find the drumkit which has been selected from the SoundLibraryPanel.  Since i've selected a SystemDrumkit, the drumkit can't be found and the error message is displayed.
       
I've pushed a quick fix for (1) to master, but i don't know about (2). I suppose you have a better idea what this property should do :smiley:

**Comment by theGreatWhiteShark** [comment]
> So this appends directly to the internal member m_sMessageFailedPreDrumkitLoad, which should explain the strange string.

Hmm. Is `append` a bad thing to do? The incentive of encapsulating a part of the message in `m_sMessageFailedPreDrumkitLoad` - which is reused at another place - is to ease the burden of the translators. This way it only appears once in the `.ts` files.

> (2): There seems to be a new song property "drumkitLookup". If this is not present in the current song, it is set to Lookup::user.
In SoundLibraryPanel Line 762, this lookup is used to find the drumkit which has been selected from the SoundLibraryPanel. Since i've selected a SystemDrumkit, the drumkit can't be found and the error message is displayed.

Ah, I see. Thanks for looking into it!

> I suppose you have a better idea about what this property should do

Jupp. Whenever the user stored a drumkit containing the same name as a system one - say *GMRockKit* - all the options in the SoundLibrary sidebar got confused and were not able to choose the proper one. This property determines whether the currently loaded drumkit is found on system level or user level (since it will be loaded just based on its name).

**Comment by mauser** [comment]
> > So this appends directly to the internal member m_sMessageFailedPreDrumkitLoad, which should explain the strange string.
> 
> Hmm. Is `append` a bad thing to do? The incentive of encapsulating a part of the message in `m_sMessageFailedPreDrumkitLoad` - which is reused at another place - is to ease the burden of the translators. This way it only appears once in the `.ts` files.

Well, you're appending the second part of the message (the name of drumkit) *permanently* to the string of the original message. I don't think that this was intended. 

The general idea of storing messages like this is not a problem. We could think about putting all "common" messages into a single class.

**Comment by theGreatWhiteShark** [comment]
> Well, you're appending the second part of the message (the name of drumkit) permanently to the string of the original message. I don't think that this was intended.

Ah, of course. I somehow thought the message was wrapped in a `QString`. Sorry.

> The general idea of storing messages like this is not a problem. We could think about putting all "common" messages into a single class.

Is there a way we can do this without invalidating them in the translations?
