### ISSUE TITLE
Tempo changes to 10bpm while playing in Song mode

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#1223]
Hydrogen version *          : Hydrogen 1.1.0-'d7d3db9a'
Operating system + version  :  Ubuntu 20.10
Audio driver + version      :  Alsa

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
When switching from Pattern Mode to Song Mode in a fresh song, Hydrogen sets the tempo to 10bpm if "Play" is pressed.

**Comment by theGreatWhiteShark** [comment]
Hmm. Can't reproduce this either (with ALSA, ubuntu 21.04, and the same commit). Does anything suspicious show up in the log?

**Comment by mauser** [comment]
Hi! 

This was also quick to find with the debugger.

At the end of `void SongEditorPatternList::patternChangedEvent()` , there is:

`		float fTimelineBpm = pTimeline->getTempoAtBar( pHydrogen->getPatternPos(), false );`

In my case, pTimeline holds no tempo markers, so the tempo will be set to 0 (which will be then MIN_BPM=10bpm, effectively..). 
It seems that this code has been introduced with b1d83dab06bb86e1b10db4a987f318a73c876fc0. Do we need to insert an "artifical" bpm marker on song load for songs which have no markers? 

It is strange that this hasn't been reported before, maybe i'm missing a part of the picture. Or not many people have the timeline enabled.

**Comment by theGreatWhiteShark** [comment]
> It seems that this code has been introduced with b1d83da.

Ups

> It is strange that this hasn't been reported before, maybe i'm missing a part of the picture. Or not many people have the timeline enabled.

Since it's disabled per default I suspect people only enable it with the intend to place tempo markers.

> Do we need to insert an "artifical" bpm marker on song load for songs which have no markers?

I would go for a hotfix in `void SongEditorPatternList::patternChangedEvent()` for now and to postpone the proper fix to 1.2.

Apart from the fact that it shouldn't be the GUI in the first place to set the tempo according to the Tempo Markers (#865) there are two bigger UX issues when placing a (hidden) tempo marker.

1. Setting the tempo with the BPM widget in the Main Toolbar with Timeline disabled is storing the particular BPM in the `Song` class. But whenever the first tempo marker is encounter, its value does overwrite the one previously set (which can not be recovered by other means than UNDO). Enabling/disabling the Timeline would resulting in losing the BPM too. (see #854)
2. As soon as `audioEngine_checkBPMChanged()` encounters a Tempo Marker the latest one will be used to overwrite the current tempo. This also renders both the Tap Tempo and the Beat Counter impossible to use. Each time they will be used to register a new tempo, it will be overwritten immediately. Same with all OSC and MIDI commands altering the BPM.

For 1.2 I would suggest we store the current tempo in `AudioEngine` and don't touch the one in `Song`. In addition, we could add an option to the preferences to automatically insert tempo markers when using Tap Tempo, Beat Counter, or tempo-altering OSC and MIDI commands.

**Comment by mauser** [comment]
Agreed, an artifical tempo marker could cause more trouble currently.. I've tried your current hotfix, it works fine for me, so postponing that to 1.2 would be totally ok. 

The "splitted" handling of the tempo (current tempo -> engine, song tempo map: song)  sounds the way to go for me..
