### ISSUE TITLE
Is the license GPL-2 or GPL-2+?

### ISSUE THREAD

**Issue by ryandesign** [hydrogen-music/hydrogen#1239]
Hi, I'm a developer with MacPorts, in which we have a port for Hydrogen and have marked it as being under the GPL-2 license, which is what it says in your README. However the source code headers that I found say GPL-2 or later. Which is it? I hope that it is actually GPL-2 or later, since you link with Qt which is licensed GPL-3. We cannot legally distribute a binary of Hydrogen if it is licensed GPL-2 only, but we could if it were licensed GPL-2 or later. And if it is GPL-2 or later, could you clarify that in the README? Thanks.

**Comment by mauser** [comment]
Hi,

good question. I've never questioned the license in the README after joining the project and it seems that i also did not as close at the license header as you did. 

So searching for any cpp files which do not include the string "any later version" (using `grep -riL "any later version"  --include *.cpp   src/` produced the files which are listed in the tables below. It seems that we have a some files with no version information, and one header file with a custom license. I found no GPl2-only files.It seems that those unlicensed files might also be problematic: https://www.gnu.org/licenses/license-list.html#NoLicense

So now the following things come to my mind..

1. We should try to put a license in the files without a license after speaking with the authors. Some of those files are my work, i can check the authors for the others and try to clear the situation.
2. Can't say if the license in Nsm.h is compatible. Maybe there is an alternative implementation, which is GPL-2 compatible? @theGreatWhiteShark , could you adress this point?
3. If the two above points are checked, can we just change the "official" license of the project? Since all file-licenses should be ok by then, this should work on my opinon without speaking with every contributor. Are there other opinions on this point?





| Filename        | License           
| ------------- |:-------------:| 
| src/gui/src/SoundLibrary/SoundLibraryDatastructures.cpp |  Empty
| src/gui/src/FilesystemInfoForm.cpp | Empty
| src/core/IO/PortaudioDriver.cpp | Empty
| src/core/IO/JackMidiDriver.cpp | Empty
| src/core/Timehelper.cpp | Empty
| src/core/Helpers/Filesystem.cpp | Empty
| src/core/Helpers/Legacy.cpp | Empty
| src/core/Helpers/Files.cpp | Empty
| src/core/Helpers/Xml.cpp | Empty
| src/core/Version.cpp |  Empty
| src/tests/RubberbandTest.cpp | Empty
| src/tests/SampleTest.cpp | Empty
| src/tests/Translations.cpp | Empty
| src/tests/MidiNoteTest.cpp | Empty
| src/tests/OscServerTest.cpp | Empty
| src/tests/TimeTest.cpp | Empty
| src/tests/PatternTest.cpp | Empty
| src/tests/main.cpp |  Empty
| src/tests/NoteTest.cpp | Empty
| src/tests/TestHelper.cpp | Empty
| src/tests/AdsrTest.cpp | Empty
| src/tests/InstrumentListTest.cpp | Empty
| src/tests/CoreActionControllerTest.cpp | Empty
| src/tests/FilesystemTest.cpp | Empty
| src/tests/XmlTest.cpp |  Empty

The same for the headers:

| Filename        | License           
| ------------- |:-------------:| 
|src/gui/src/precompiled.h | Empty 
|src/gui/src/SoundLibrary/SoundLibraryDatastructures.h | Empty
|src/gui/src/UndoActions.h | Empty
|src/gui/src/FilesystemInfoForm.h | Empty
|src/core/Basics/ExponentialTables.h | Empty 
|src/core/Nsm.h | [Custom License](https://github.com/hydrogen-music/hydrogen/blob/master/src/core/Nsm.h)
|src/core/IO/JackMidiDriver.h | Empty
|src/core/Timehelper.h | Empty
|src/core/Helpers/Translations.h | Empty
|src/core/Helpers/Legacy.h | Empty
|src/core/Helpers/Filesystem.h | Empty
|src/core/Helpers/Xml.h | Empty
|src/core/Helpers/Files.h | Empty
|src/core/Version.h | Empty
|src/tests/TestHelper.h | Empty
|src/tests/TimeTest.h | Empty
|src/tests/AdsrTest.h | Empty
|src/tests/PatternTest.h | Empty
|src/tests/XmlTest.h | Empty
|src/tests/OscServerTest.h | Empty
|src/tests/CoreActionControllerTest.h | Empty 
|src/tests/FilesystemTest.h | Empty

**Comment by mauser** [comment]
Ah, and we should have a github check for Pull-Requests to prevent files from having no license :)

**Comment by theGreatWhiteShark** [comment]
> Can't say if the license in Nsm.h is compatible. Maybe there is an alternative implementation, which is GPL-2 compatible? @theGreatWhiteShark , could you adress this point?

It holds the [ISC license](https://en.wikipedia.org/wiki/ISC_license) which - according to Wikipedia - is GPL compatible.

> Since all file-licenses should be ok by then, this should work on my opinon without speaking with every contributor. Are there other opinions on this point?

I think so too. Especially since the file headers specify GPL2+ it feels more like a bug fix because a person clicked the wrong template file when creating the repo.

**Comment by mauser** [comment]
@jeremyz , @cominu , @elpescado , @cme , @blablack , @wolkstein, @xnakos, @theGreatWhiteShark   :

Hey everyone :smiley: 

at some time, you contributed to a file in Hydrogen which has no copyright statement. Would you agree to licensing your contribution as "GPL 2 or newer", as the rest of the Hydrogen source code ?

**Comment by jeremyz** [comment]
Yes, sure.

**Comment by cme** [comment]
Oops, did I leave a license off something? 

Yes absolutely!

**Comment by pvint** [comment]
Yes, that's good with me!

**Comment by mauser** [comment]
@ryandesign: The README has been updated to "GPLv2+". This has been erronously introduced when created the markdown version of the README for github. All source code have "GPLv2 or later" headers. We have now also added a copyright header to all relevant files which were missing such information.

**Comment by elpescado** [comment]
Yes, sure.
