### ISSUE TITLE
[bug] Mouse icon remains of type "hand" if you paste notes

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1254]
Hydrogen version *          : 1.1 master
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@cme 
way to reproduce: 
enter notes like this
![image](https://user-images.githubusercontent.com/54219881/116398045-9f049280-a827-11eb-8b88-c0a0dc09e79a.png)

select and copy, then move the keyboard cursor to the second note
![image](https://user-images.githubusercontent.com/54219881/116398293-ebe86900-a827-11eb-900c-06724b9098fb.png)

ctrl+V (paste) and then press Enter (or just one of the ways, try it...)
![image](https://user-images.githubusercontent.com/54219881/116398540-34078b80-a828-11eb-8bf0-c48b37a21356.png)

press elsewhere in the drum pattern editor, then press Ok in the dialog.
![image](https://user-images.githubusercontent.com/54219881/116398884-93659b80-a828-11eb-8d46-064ff0096055.png)

=> mouse cursor icon remains of type "hand"

**Comment by cme** [comment]
The problem is actually a bit more general -- if you cancel any keyboard move with a mouse click it leave the mouse cursor as it was.

Thinking about it, changing the mouse cursor at all seems fundamentally wrong during a keyboard gesture, as the only thing the mouse can do at that point is cancel the gesture. Having something indicate that the keyboard gesture will be a copy vs. a move is useful, but not at the expense of misleading the user into thinking the mouse will do something other than what it does.

So I'll disable changing the mouse cursor for keyboard gestures.
