### ISSUE TITLE
Songs appear "unmodified" after autosave

### ISSUE THREAD

**Issue by cme** [hydrogen-music/hydrogen#1261]
Hydrogen version *          :  12fbd2425c71a7f7236866c83e572b0b3e7df7cd
Operating system + version  : all
Audio driver + version      :  all

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hydrogen periodically auto-saves the current song (every minute). After saving, the `IsModified` flag is cleared, and quitting Hydrogen or opening a new song will not show a warning about unsaved data.

This is counter to most user expectation, and allows such sequences as:
  - modify song
  - wait a minute
  - close song without saving, or seeing a warning
  - re-open song
  - continue modifications, old modifications are silently lost

I strongly suspect this is the cause of #1039 .

**Comment by theGreatWhiteShark** [comment]
Nice catch!

I also find the `.autosave` files to be quiet annoying in general. One has to manually check whether they were saved more recently than the original file and when one decides to open them instead another `.autosave` will be appended.

Just an idea but for 1.2 we could hide the `.autosave` files in the Project > Open dialog and display a popup dialog when an autosave file associated with the selected file is present saying something like "There are unsaved changes for the selected song. Do you want to restore them instead?" If the user selects "Yes", the `.autosave` version would be loaded, all automatic savings go to this very file and the user does need to hit "Save" explicitly to overwrite the selected file. So, if "Yes" turned out to be the improper decision, one only needs to reload or reopen the song to load the earlier checkpoint. This might also be beneficial for the `SoundLibrary` which does not display the `.autosave` versions at all.
