### ISSUE TITLE
Build of AppVeyor image for Windows target fails 

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1274]
Hydrogen branch          : `development`
Operating system + version  : Windows

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Since a couple of weeks the AppVeyor image of the Windows build does constantly fail with the following error message:

> C:\projects\hydrogen\src\core\AudioEngine.cpp:23:10: error: 'core/AudioEngine.h' file not found [clang-diagnostic-error]
> #include <core/AudioEngine.h>
>         ^
> 1 error generated.

e.g. in https://ci.appveyor.com/project/mauser/hydrogen/builds/39176767/job/r3pciwt1o7iw9iix

I took a look into the `.appveyor.yml` file - without understanding the peculiarities of the framework - but couldn't find anything suspicious?

@mauser could you have a look at it? Seems to be introduced by the refactoring of the Audio Engine.

**Comment by mauser** [comment]
Hey ho, 

i'm innocent, as it seems :smiley:  The root of the problem is pull request #1243, which changed the way cmake looks for `clang-tidy`. On windows, this makes cmake use clang instead of the mingw-gcc toolchain.  The AudioEngine header is just the first one to be included, but I don't know why clang does not find it :-/  
It seems that the problem is that`SET(CMAKE_CXX_CLANG_TIDY clang-tidy)` is called in the "IF" body at line 99 as well as the "IF" body at 107, so it is also set even if WANT_CLANG_TIDY is false. This should be fixed now on the development branch.

But it seems that there is also a second probem. In Hydrogen::toQString(), there is a call to std::ctime with m_CurrentTime.tv_sec as an argument. The problem is that m_CurrentTime is of type `timeval`, which is platform-dependent. On linux, tv_sec is a member with type `time_t`, on windows it is just `long`. This creates a problem because std::ctime expects `time_t`. Should we just print out the `long` on windows?

**Comment by theGreatWhiteShark** [comment]
> The root of the problem is pull request #1243

Darn! :smile: This happened at the same time the AppVeyor images where revised so I thought changing the order of things in the CMakeLists shouldn't do any harm.

> On windows, this makes cmake use clang instead of the mingw-gcc toolchain.

Doesn't this imply the build for windows will fail if done with the `WANT_CLANG_TIDY` option and it would be better to wrap the whole clang-tidy part in an `IF ( NOT MINGW )`?

> But it seems that there is also a second probem. In Hydrogen::toQString(), there is a call to std::ctime with m_CurrentTime.tv_sec as an argument. The problem is that m_CurrentTime is of type timeval, which is platform-dependent. On linux, tv_sec is a member with type time_t, on windows it is just long. This creates a problem because std::ctime expects time_t. Should we just print out the long on windows?

Yes! The `toQString` debugging methods - especially the one of the `Hydrogen` class - are not final. The short version in particular takes quite some time to fine tuning and has to be tested/used in different contexts to not flood the screen but still gives all relevant information. I decided to do this incrementally while using them for debugging as I don't want to waste to much time on this and having some ill-formatted information is better than having none. But they definitely should break the build/cause a segfault.

**Comment by theGreatWhiteShark** [comment]
Closed with #1278
