### ISSUE TITLE
Correct FSF address in LICENSE

### ISSUE THREAD

**Issue by tartina** [hydrogen-music/hydrogen#1292]
Hydrogen version *          : all
Operating system + version  : all
Audio driver + version      : all

The FSF address reported in COPYING is the old one, the new one is
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

See also https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

This results in a warning by rpmlint packaging hydrogen for Fedora.

**Comment by theGreatWhiteShark** [comment]
Haha. That's a quite thorough linter. I would suggest to drop the postal address altogether and to use an URL, like in the  [GNU GPL howto](https://www.gnu.org/licenses/gpl-howto.html)

> You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>

instead of the current

>  You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
