### ISSUE TITLE
Patterns enhancements: Visual feedback when a pattern has been changed...

### ISSUE THREAD

**Issue by andrew-dotdot** [hydrogen-music/hydrogen#130]
Because I usually start with some basic patterns and then embellish them with fills and small variations, I find myself right-click saving and loading a lot of Patterns. I've found no better or easier way to duplicate patterns.

In this light, some useful enhancements to Patterns would be the following:

1) Some visual feedback when a pattern has been changed (and needs to be saved), for example an asterisk displayed next to the name of the Pattern.
2) The option to save all previously-saved patterns with unsaved changes

I'm using 0.9.6-beta 1 on osx Mavericks. I'm finding Hydrogen to be quite useful. Great job! This is my first post here.

**Comment by thijz** [comment]
related to #232

**Comment by theGreatWhiteShark** [comment]
> Because I usually start with some basic patterns and then embellish them with fills and small variations, I find myself right-click saving and loading a lot of Patterns. I've found no better or easier way to duplicate patterns.

As @xjjx stated there is the "duplicate" feature when right clicking a pattern name in the song editor as well as loads of new ways to fast and efficiently copy patterns or individual parts of them using mouse or keyboard since v1.1 of Hydrogen.

I think there is no need anymore to do this duplication in such a file-based manner and will close this issue for now. But please feel free to reopen it if you think otherwise.
