### ISSUE TITLE
Hydrogen 1.1.0 error on Ubuntu 18.04

### ISSUE THREAD

**Issue by antonio-petricca** [hydrogen-music/hydrogen#1368]
Hydrogen version *          : 1.1.0
Operating system + version  :  Ubuntu 18.04
Audio driver + version      :  not applicable

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I built Hydrogen from sources and I get the error `libhydrogen-core-1.1.0.so: cannot open shared object file: No such file or directory`.

Thank you!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by antonio-petricca** [comment]
In order to get rid of it I had to generate the deb package and use it in place of the `make install`.

**NB:** the package is build ever as `1.0.0` and not `1.1.0`, but it works.

**Comment by theGreatWhiteShark** [comment]
Building deb packages is something only package maintainer need to do.

From the [INSTALL.md](https://github.com/hydrogen-music/hydrogen/blob/master/INSTALL.md):

---

### Running Hydrogen

After installation, Hydrogen's binaries can be found in `CMAKE_INSTALL_PREFIX/bin`.
If this path is not in your `PATH` environment variable, consider adding it to it.

If Hydrogen doesn't start, and you have the above message :

```
… error while loading shared libraries: libhydrogen-core-1.1.0.so …
```

it's because Hydrogen's shared library is not found.
You can verify this with the following command

```bash
ldd CMAKE_INSTALL_PREFIX/bin/hydrogen | grep 'not found'
```

To fix it, you can use `LD_PRELOAD` or `LD_LIBRARY_PATH` environment variables,
or configure `ldconfig` (see man ldconfig, man ld.so).

Another option is to set the `cmake` option
`-DCMAKE_INSTALL_PREFIX=/usr`, recompile, and reinstall Hydrogen.
But be aware that you will certainly overwrite Hydrogen files that you might have
installed with your distribution's package manager.

see [issue#677](https://github.com/hydrogen-music/hydrogen/issues/677)

**Comment by theGreatWhiteShark** [comment]
Hey @antonio-petricca, were you able to fix the problem with the instructions above or did you experience a different problem after all?
