### ISSUE TITLE
Into infinite loop playing demo

### ISSUE THREAD

**Issue by worikgh** [hydrogen-music/hydrogen#1549]
Hydrogen version *          : Freshly built clone from master
Operating system + version  : patchboxos (Rasparian variant)
Audio driver + version      : jackd 1.2.12

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Ctl-D
`TR808kit-demo.h2song`
Click Play

Plays first pattern OK
Then plays first half of second pattern and starts having "X-runs" and stuttering,. then stops.
A lot of things to the console

```
~/hydrogen $ ./hydrogen 2>&1 /tmp/hydrogen.out
~/hydrogen $ wc -l /tmp/hydrogen.out 
7611 /tmp/hydrogen.out
/hydrogen $ cat /tmp/hydrogen.out | sort | uniq -c | sort -n
      1 
      1 Copyright 2002-2008 Alessandro Cominu
      1 Copyright 2008-2022 The hydrogen development team
      1 (E) Filesystem::check_permissions /home/patch/.hydrogen/data/emptySong.h2song is not a file
      1 Hydrogen 1.1.1-'ffe835d7' [Mar 27 2022]  [http://www.hydrogen-music.org]
      1 Hydrogen comes with ABSOLUTELY NO WARRANTY
      1 libEGL warning: DRI2: failed to authenticate
      1 "No carrier"
      1 This is free software, and you are welcome to redistribute it under certain conditions. See the file COPYING for details.
      2 (E) EventQueue::push_event Event queue full, lost event type 9 value 10
      3 (E) EventQueue::push_event Event queue full, lost event type 9 value 15
      4 (E) EventQueue::push_event Event queue full, lost event type 9 value 5
      4 (E) EventQueue::push_event Event queue full, lost event type 9 value 7
      5 (E) EventQueue::push_event Event queue full, lost event type 9 value 6
      6 (E) EventQueue::push_event Event queue full, lost event type 9 value 3
     10 (E) EventQueue::push_event Event queue full, lost event type 9 value 13
     10 (E) EventQueue::push_event Event queue full, lost event type 9 value 2
     11 (E) EventQueue::push_event Event queue full, lost event type 9 value 14
     19 (E) EventQueue::push_event Event queue full, lost event type 9 value 12
     23 (E) EventQueue::push_event Event queue full, lost event type 9 value 9
     26 (E) EventQueue::push_event Event queue full, lost event type 9 value 8
     42 (E) EventQueue::push_event Event queue full, lost event type 9 value 1
     70 (E) EventQueue::push_event Event queue full, lost event type 11 value 1
    254 (E) EventQueue::push_event Event queue full, lost event type 11 value 0
   1488 (E) EventQueue::push_event Event queue full, lost event type 8 value 0
   2565 (E) EventQueue::push_event Event queue full, lost event type 2 value 0
   3061 (E) ::static int H2Core::AudioEngine::audioEngine_process(uint32_t, void*) Failed to lock audioEngine in allowed 0 ms, missed buffer
```

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by cme** [comment]
Hi a couple more questions.

* Which RasPi hardware are you using?
   *  how heavily loaded does the system get before things go wrong?
   * Relatedly, can this be repeated with a release build rather than a debug build?
 * How repeatable is this?

The log appears to show the GUI falling a bit behind in processing messages, then being swamped with buffer underrun events. That's *probably* one of two things. Either it's a simple deadlock for the audio lock, or maybe...  I'm wondering if the adding of extra messages (which I did recently...) has managed to cause inelastic processing time behaviour: causing more CPU load to print the messages making it harder to recover to a stable state.

I notice also there's an error from libEGL. Hydrogen doesn't use this itself, but I guess it might be used by Qt? And this might indicate a lack of hardware-accelerated rendering that might explain why the GUI falls behind.

**Comment by theGreatWhiteShark** [comment]
Another thing the log hints is that Hydrogen did successfully connect to the JACK server and it is the latter which informs Hydrogen about the XRUN events. It's of course entirely possible some things go wrong inside Hydrogen but it can also be the JACK buffersize being set too low for the hardware at hand. Could you run the application with the `hydrogen -VDebug`? Maybe the full log will hint what's going wrong.

In addition, do you have to same problem when choosing a different audio driver?

**Comment by worikgh** [comment]
> Which RasPi hardware are you using? 

Raspberry PI 4 With 2GB

> how heavily loaded does the system get before things go wrong?

Not very.  `htop` and `iotop` running and everything is juts ticking along

> How repeatable is this?

100%

> I notice also there's an error from libEGL. Hydrogen doesn't use this itself, but I guess it might be used by Qt? And this might indicate a lack of hardware-accelerated rendering that might explain why the GUI falls behind.

I have done nothing to accelerate rendering.  It is "out of the box"

> Relatedly, can this be repeated with a release build rather than a debug build?

0.9.7 is playing the demos OK. Not crashing

**Comment by worikgh** [comment]
More info.

The local version (from github) behaves differently when I have `hydrogenb` instaled from repositories (o.9.7)

I get this:
![image](https://user-images.githubusercontent.com/5387413/160549277-aa94c17f-49b3-41e1-b309-38921a761ace.png)

**Comment by worikgh** [comment]
Running: `~/hydrogen $ ./hydrogen -VDebug 2>&1 | tee /tmp/log`

The log is (21k lines)
I ran it again and made a new pattern as it looped.  It had the same problem.
I do not think thi sis the demo
I ran: `~/hydrogen $ ./hydrogen -VDebug 2>&1 | tee /tmp/log3` and it is smaller.  I attached both logs
[logs.tar.gz](https://github.com/hydrogen-music/hydrogen/files/8368794/logs.tar.gz)

**Comment by cme** [comment]
Ah, great, thank you!

So, theoretically I should have been able to spot this from the previous log. It looks like the slack time calculation in the audio engine somehow gets the answer that there's zero slack time available to wait for the audio system lock when the GUI is holding it, so it fails straight away.

I wonder how it got into that state. 

However, looking at the code, I can see that once it gets *into* that state, it will never get out of it again because the exit path doesn't reset the processing time. There's a couple of other things here that I should fix too. I'll take a look! Many thanks for finding this and the helpful logs!

**Comment by cme** [comment]
Hi @worikgh, I've changed the buffer slack calculation in branch [`dev-audio-engine-timing`](https://github.com/hydrogen-music/hydrogen/tree/dev-audio-engine-timing) to be able to recover from high load situations, but I'm less confident now that this is actually the cause of your issue since it actually *should* already be able to recover from the zero-wait condition as soon as it does manage to acquire the lock for a buffer period. It sounds like maybe the system is getting bogged down or the GUI is somehow locking for too long, but this *shouldn't* be the case since the critical sections in the GUI are really fairly small and short.

I guess maybe it's possible that the audio system is just failing to recover elegantly from the missed buffer condition? Does that sound plausible @theGreatWhiteShark ?

@worikgh if you want to see if this fixes your problem in order to make progress on whatever else you were doing, I'd be grateful if you could give `dev-audio-engine-timing` a try. Thanks! :)

**Comment by theGreatWhiteShark** [comment]
> I guess maybe it's possible that the audio system is just failing to recover elegantly from the missed buffer condition? Does that sound plausible @theGreatWhiteShark ?

I'm lacking background knowledge to judge whether this might be plausible. But it sounds at least quite familiar. From the user perspective I already encountered a number of programs that were both freezing at some point and unable to recover. Those zombies usually require to reboot the system. As occurs in a variety of program developed/maintained by different persons, it feels like a problem at system-level. But, well, that's nothing more than a guess. 

In addition, when fixing a bug I encountered in a broken local ALSA setup I also experienced 2-3 valid process cycles of the audio engine before the ALSA module choked on something and refused to work anymore. But I got different error messages and the problem might not even be related.

> I ran: ~/hydrogen $ ./hydrogen -VDebug 2>&1 | tee /tmp/log3 and it is smaller. I attached both logs
[logs.tar.gz](https://github.com/hydrogen-music/hydrogen/files/8368794/logs.tar.gz)

Thanks a lot! 

But we need to add the buffer size of the JACK server to the log messages...

@worikgh could you report what parameters you set for the buffer size and period of the JACK server?

**Comment by worikgh** [comment]
It is working perfectly now.

> @worikgh could you report what parameters you set for the buffer size and period of the JACK server?

Unsure.  I choose the defaults for patchbox

qjackctl reports 
sample rate: 48000
Frames/Periuod: 1024
Periods/Buffer: 2

I have:

```
/hydrogen $ git log -n 1
commit 0afd93716b67d2f13c8505f9d6102af3c9f6d1ff (HEAD -> master, origin/master, origin/HEAD)
Merge: 676dbf8c 205d82f2
Author: theGreatWhiteShark <thetruephil@googlemail.com>
Date:   Mon Apr 4 08:11:57 2022 +0200

    Merge pull request #1553 from theGreatWhiteShark/phil-further-fixes
    
    Phil further fixes
```

**Comment by theGreatWhiteShark** [comment]
Hmm. Strange. There were no changes affecting the audio driver recently. Maybe it was a problem in the system's audio setup after all.

Anyway, I'm glad it works now :)
