### ISSUE TITLE
Midi output not working for both ALSA and JACK.

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#1636]
### Discussed in https://github.com/hydrogen-music/hydrogen/discussions/1635

<div type='discussions-op-text'>

<sup>Originally posted by **king112ola** August 16, 2022</sup>
Hello Hydrogen team :wave: 

Receiving Midi Works fine. However, I cannot send midi to other applications, e.g. Ardour.

Version: 
Hydrogen 1.1.1
Ardour 6.9.0
Fedora 36</div>

**Comment by theGreatWhiteShark** [comment]
Hey @king112ola,

Per default notes played back in Hydrogen do not trigger MIDI events. You have to explicitly enable it by setting an output MIDI channel for the corresponding instrument http://hydrogen-music.org/documentation/manual/manual_en.html#chpt.instrument_editor.midi_out_settings

**Comment by king112ola** [comment]
> 

Thank you for the reply!

**Comment by theGreatWhiteShark** [comment]
Okay. I just took a look and MIDI note output itself is working fine.

It's not intuitive though because if the MIDI output channel in the Instrument  Editor is set to `off` no MIDI notes for the corresponding instrument will be send. Now, it just so happens that `off` is the default value for all instruments in the GMRockKit. Setting a MIDI output with this kit loaded will result in no MIDI output at all until all instrument channels are manually set to a valid channel. That's not good UX at all.

But there is indeed something broken within CC MIDI feedback. I'll have a look
