### ISSUE TITLE
Timing humanization (and swing) doesn't work

### ISSUE THREAD

**Issue by cme** [hydrogen-music/hydrogen#1655]
Hydrogen version *          : master (c69553da03ff5612fc11ea85e0da1d4f00fbb297)
Operating system + version  : all
Audio driver + version      :  all

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Timing humanisation and swing don't currently do much of anything at all. The humanization delay is set in `AudioEngine::updateNoteQueue` but the only place it's read (via `Note::get_humanization_delay`) are in comparison of notes and in `Sampler::renderNote*` only negative values are used, which seems wrong.

Also the offset calculation for swing looks wrong

```
computeFrameFromTick( nnTick + MAX_NOTES / 32., &fTickMismatch ) *
pSong->getSwingFactor() -
computeFrameFromTick( nnTick, &fTickMismatch );
```

This subtracts the current frame number (based at 0) from a frame number scaled by the swing factor: the scaling should be applied to the difference between frames.

The quantized application of swing to notes that are exactly on the odd 1/16ths will not meet with users expectations if there happen to be other notes (eg 1/32nd grace notes) on other subdivisions since these won't be retimed at all.

It's not clear exactly what the right behaviour in these circumstances would be (a linear interpolation between timeframes? Something else?) but the quantized one seems least likely to be expected by users.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by theGreatWhiteShark** [comment]
> The humanization delay is set in AudioEngine::updateNoteQueue but the only place it's read (via Note::get_humanization_delay) are in comparison of notes and in Sampler::renderNote* only negative values are used, which seems wrong.

`Note::__humanize_delay` is also read in [Note::computeNoteStart()](https://github.com/hydrogen-music/hydrogen/blob/master/src/core/Basics/Note.cpp#L238).  `__position` specifies the position of the `Note` in ticks. But this alone is not sufficient to determine the position in frames - in case the Timeline is deactivated - which is the relevant information for the `Sampler` to render it. If e.g. the users alters the tempo of the song after the note was queued by `AudioEngine::updateNoteQueue` but before/while the `Sampler` is rendering it, the tick size changes and the former note onset in frames is invalidated. I introduced `computeNoteStart()` and some helper variables to 1. allow the `Sampler` to detect those tick size mismatches itself and 2. to more easily handle enqueued note in case a tempo, song size etc. change occurred. 

> in Sampler::renderNote* only negative values are used, which seems wrong.

Hmm. Indeed. At least the comments in `Note::computeNoteStart()` are suggesting the `Sampler` should take care of only the positive values. I think this calls for a unit of the humanization. These are things that should work. (IIRC negative values must be taken into account immediately in `Note::computeNoteStart()` in order for `AudioEngine::processPlayNotes()` to take the lead into account. But when doing the same for the lag the note queue of the AudioEngine chokes on it so these are left to handle for the `Sampler`. But this might be already outdated.)

> Also the offset calculation for swing looks wrong

Yeah, I found this one to be quite strange too. It feels like someone put it there just to work with his or her style of programming patterns.

> It's not clear exactly what the right behaviour in these circumstances would be (a linear interpolation between timeframes? Something else?) but the quantized one seems least likely to be expected by users.

Especially since the nominator and denominator of the pattern length do not specify a measure. If they would, we could probably just look up a definition from a music theory book.

**Comment by cme** [comment]
Do you think this issue ought to block a 1.2 beta release? It feels like "yes" to me. I'm wondering whether to cherry pick midi fixes to the 1.1 release branch and do a point release to make those available, if we can't do a 1.2 beta too soon.

**Comment by theGreatWhiteShark** [comment]
> Do you think this issue ought to block a 1.2 beta release? It feels like "yes" to me.

Yeah, I think so too. IMHO audio engine and sampler are so fundamental they just must work before the release. Rendering issues, broken buttons etc. are at another level and can be patched later on (e.g. in a 1.2 beta2).

I'm almost done with a large patch of audio engine that fixes a bigger conceptional flaw and hopefully also gets rid off the playhead glitches. But with my current amount of time to spare it will probably need a couple more days. I'll fix the humanization issues later on and also cover them with unit tests so they won't break again without us noticing.

> I'm wondering whether to cherry pick midi fixes to the 1.1 release branch and do a point release to make those available, if we can't do a 1.2 beta too soon.

We should most probably do so. Even if we could get 1.2 beta on the way by tomorrow it will still take some time till the final 1.2 release and most distributions only package stable releases.

**Comment by cme** [comment]
> I'm almost done with a large patch of audio engine that fixes a bigger conceptional flaw and hopefully also gets rid off the playhead glitches. But with my current amount of time to spare it will probably need a couple more days. I'll fix the humanization issues later on and also cover them with unit tests so they won't break again without us noticing.

Excellent! Sounds awesome :)

> > I'm wondering whether to cherry pick midi fixes to the 1.1 release branch and do a point release to make those available, if we can't do a 1.2 beta too soon.
> We should most probably do so. Even if we could get 1.2 beta on the way by tomorrow it will still take some time till the final 1.2 release and most distributions only package stable releases.

I'll get on that if I have time this weekend :)

**Comment by theGreatWhiteShark** [comment]
I just realized we also apply velocity humanization to the metronome. This can't be right.

**Comment by theGreatWhiteShark** [comment]
While working on this issue I realized that timing humanization only affects notes obtained from the patterns within Hydrogen. Notes retrieved via MIDI input or realtime events - like using the virtual keyboard - are not affected. In terms of pitch and velocity humanization, however, all kinds of notes named above are affected.

It feels wrong to treat timing humanization different than the other ones. What do you think, should be add it to realtime and MIDI notes too? Or should we apply no humanization to them at all? Or just leave things as is and mention it in the docs? I tend towards the first option.

**Comment by theGreatWhiteShark** [comment]
Velocity adjustments by the automation path are similar. They only affect notes picked up from patterns but no MIDI or real time ones.
