### ISSUE TITLE
No CLI output in Windows

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1671]
Hydrogen version *          : 1.2 | 891bb7f293c8219411fa060e3dd7758635d549eb
Operating system + version  :  Windows
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

While using a recent Hydrogen version in Windows I found that CLI arguments in both Windows CMD (command something) and Powershell, like `--help` or `--version` do not produce output at all.

In older versions, e.g. the 1.1. release, these arguments would open an additional window displaying the corresponding output (its a bit weird to have it in another dialog rather than in the console itself but that's of no priority).

I doubt that a lot of folks do you Hydrogen via the CLI in Windows. But displaying version, help text and the corresponding license notice should work nevertheless.

**Comment by elpescado** [comment]
Is it even possible? If I remember correctly, MS Windows maintains distinction between console and GUI applications, where the latter don’t even have a connection to the console and the selection is done at the compilation time (-mwindows switch I think).PrzemekWiadomość napisana przez theGreatWhiteShark ***@***.***> w dniu 11.11.2022, o godz. 14:30:﻿
Hydrogen version *          : 1.2 | 891bb7f
Operating system + version  :  Windows
Audio driver + version      :

While using a recent Hydrogen version in Windows I found that CLI arguments in both Windows CMD (command something) and Powershell, like --help or --version do not produce output at all.
In older versions, e.g. the 1.1. release, these arguments would open an additional window displaying the corresponding output (its a bit weird to have it in another dialog rather than in the console itself but that's of no priority).
I doubt that a lot of folks do you Hydrogen via the CLI in Windows. But displaying version, help text and the corresponding license notice should work nevertheless.

**Comment by theGreatWhiteShark** [comment]
I just check one other application (Emacs) and it printed its output right into the command line (including all logs when opening it as a GUI)
