### ISSUE TITLE
Failure loading drumkits (made with Shuriken)

### ISSUE THREAD

**Issue by seanjean3000** [hydrogen-music/hydrogen#1725]
Hydrogen version *          : 1.2.0-beta1
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I am trying to make Hydrogen drumkits by slicing up loops in Shuriken (https://rock-hopper.github.io/shuriken/) and using that program's option to export to Hydrogen format--but when I try to open the kits in Hydrogen, the individual instruments show up with little yellow warning signs and I get the message "One or more samples for this instrument failed to load. This may be because the songfile uses an older default drumkit. This might be fixed by opening a new drumkit."

Shuriken doesn't appear to have been updated in several years, so is it possible that the drumkit format has changedt? Is there a way I can try to troubleshoot what's going on, or maybe some changes I need to make to the drumkit file?

I should also mention that the kits I'm trying to make have a lot of pieces / instruments (I'd say at least 50 or more), so maybe that's an issue? Is there a limit to the number of instruments in a kit?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by theGreatWhiteShark** [comment]
Hey @seanjean3000 

> Shuriken doesn't appear to have been updated in several years, so is it possible that the drumkit format has changedt? Is there a way I can try to troubleshoot what's going on, or maybe some changes I need to make to the drumkit file?

Yes, it changed. But if you were able to load them with previous versions you should be still able to load them in 1.2.0-beta1. Otherwise this is a regression bug.

Could you provide one of these kits? Maybe a minimal one?

> I should also mention that the kits I'm trying to make have a lot of pieces / instruments (I'd say at least 50 or more), so maybe that's an issue? Is there a limit to the number of instruments in a kit?

Yes, it is set in here https://github.com/hydrogen-music/hydrogen/blob/master/CMakeLists.txt#L187 and compiled into Hydrogen. Per default 1000 instruments are supported. But you can increase it and compile a custom version.

**Comment by seanjean3000** [comment]
Thanks for the quick reply--that's awesome. I can't get back to it tonight unfortunately, but I will try for tomorrow to A) test one of these kits in an earlier version of Hydrogen and B) provide one for testing.

Good to know the limit on instruments is 1000--I can't see myself ever hitting that wall.

**Comment by seanjean3000** [comment]
I tried to load a kit I made into an earlier version of Hydrogen on an old computer, but that failed for different reasons (which I will let be).

For this though, I found the log file and it shows some errors:
[31m(E) Filesystem::mkdir unable to create directory : /home/user/.hydrogen/data/drumkits/JazzKit/drumkit.xml[0m
[31m(E) Drumkit::save Unable to export drumkit [JazzBreaker] to [/home/user/.hydrogen/data/drumkits/JazzKit/drumkit.xml]. Could not create drumkit folder.[0m
[31m(E) Filesystem::mkdir unable to create directory : /home/user/.hydrogen/data/drumkits/JazzKit_h2/drumkit.xml[0m
[31m(E) Drumkit::save Unable to export drumkit [JazzBreaker_h2] to [/home/user/.hydrogen/data/drumkits/JazzKit_h2/drumkit.xml]. Could not create drumkit folder.[0m

**Comment by theGreatWhiteShark** [comment]
> For this though, I found the log file and it shows some errors:
�[31m(E) Filesystem::mkdir unable to create directory : /home/user/.hydrogen/data/drumkits/JazzKit/drumkit.xml�[0m
�[31m(E) Drumkit::save Unable to export drumkit [JazzBreaker] to [/home/user/.hydrogen/data/drumkits/JazzKit/drumkit.xml]. Could not create drumkit folder.�[0m
�[31m(E) Filesystem::mkdir unable to create directory : /home/user/.hydrogen/data/drumkits/JazzKit_h2/drumkit.xml�[0m
�[31m(E) Drumkit::save Unable to export drumkit [JazzBreaker_h2] to [/home/user/.hydrogen/data/drumkits/JazzKit_h2/drumkit.xml]. Could not create drumkit folder.�[0m

This is related to a small bug I fixed [recently[(https://github.com/hydrogen-music/hydrogen/pull/1723). It just affects the upgrade of drumkits of older format to a more recent one. It does not affect the loading of the samples itself. (But due to the upgrade it is possible that paths of samples Hydrogen fails to load are removed from the `drumkit.xml` files and a fresh export from Shuriken might be required to reproduce the original load issue)

**Comment by seanjean3000** [comment]
I wenr back to 1.0.1 and the Shuriken kits are working there. Maybe it was an issue with building the beta that was causing the issue? Anyway I'm rolling now. Looking forward to seeing the new version though, the GUI improvements are nice

**Comment by theGreatWhiteShark** [comment]
I just created a small drumkit using `Shuriken` myself and it turned out to be a typo in our code base.

Could you check whether #1731 solves your problems?

**Comment by seanjean3000** [comment]
Yes, solved--thanks!

**Comment by theGreatWhiteShark** [comment]
Awesome!
