### ISSUE TITLE
Why must hydrogen drum kits be a rolled up archive? It leads to needless duplication of samples, especially for conversion from sfz

### ISSUE THREAD

**Issue by Bracket-H** [hydrogen-music/hydrogen#1733]
If hydrogen (by the way, that's an awful name and mucks up internet searches) could just read a plaintext file with the sample locations in there...then it would be no problem, or rather, less of a problem, to use something like "sm drums", which is ~2.2 gigabytes.

Rolling that into a tarball just because hydrogen (by the way, an awful name that mucks up internet searches) wants to be the special snowflake, it would have to be ~4 gigs, just in case I'd want to use the sfz somewhere else.

Lame.
(by the way, an awful name for a codec, it mucks up internet searches)

**Comment by theGreatWhiteShark** [comment]
> hydrogen (by the way, that's an awful name and mucks up internet searches)

:smile: That's not how it works. One does not rename an established application or product just because at some point in time there is a second product with better SEO in some search engine. When searching for something specific in the web, try to add some context to help the search engine to determine what you are actually looking for, e.g. using "hydrogen drum" instead of "hydrogen". 

>  hydrogen [...] could just read a plaintext file with the sample locations in there

Well, it does. Hydrogen drumkits are folders containing samples and a `drumkit.xml` file listing - among other things - the names of all contained samples. These sample files can be proper .wav files or links to samples in other locations. So, by replacing them with links you can very well have proper kits of the size of some ~100KB.

What probably got you confused is that the tarball looks like a solid file. But it is actually a compressed archive containing many files (in our case it contains the drumkit folder). Depending on your OS you can double click the file and view its content. Having to download just a single .h2drumkit instead of manually putting the definition file as well as all individual samples together is more easy (and requires less bandwidth due to the compression).

**Comment by elpescado** [comment]
> If hydrogen (by the way, that's an awful name and mucks up internet searches)

Pro tip: use "hydrogen drum machine" search query

> And running it with midi out as a pattern source to something like qsampler, well.
> Hydrogen plays its own sound lol, and if you delete the layers of the instrument then no midi data is generated.

Pro tip: Hit master "Mute" button in mixer window.

**Comment by theGreatWhiteShark** [comment]
I'll lock the conversation for now as the original issue you referenced in the title was addressed and this is a place software-related issues and not personal ones can be discussed in public.

You are as welcome as anyone else to open issues and discuss here but please try to stick to some netiquette in the future. Namely, to open separate issues for separate problems instead of attempting to discuss everything in one place and try to use a more grown-up language. Especially the latter will help us to take your problems more seriously.

> Also, I just found out that hydrogen does not support subfolders for samples

In the most recent version of Hydrogen you can use sample paths relative to the drumkit.xml definition file. By entering `./SUBFOLDER_NAME/SAMPLE_NAME` you can also construct a drumkit using subfolders.
