### ISSUE TITLE
Gimme A Hand 1.0 drumkit gets errors when loading

### ISSUE THREAD

**Issue by treborh** [hydrogen-music/hydrogen#1787]
Hydrogen version *          :1.2.0-beta
Operating system + version  : Ubuntu 23.04
Audio driver + version      : ALSA

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

31m(E) Drumkit::save Unable to export drumkit [Gimme A Hand 1.0] to [/usr/share/hydrogen/data/drumkits/Gimme A Hand 1.0/drumkit.xml]. Could not create drumkit folder.[0m

**Comment by theGreatWhiteShark** [comment]
Hydrogen does try to update your drumkits inplace whenever they do not match the latest format. Inplace in you example would mean inside _/usr/share/hydrogen/data/drumkits/_. But for this folder you do not have write premissions and Hydrogen is not able to perform the backup. Copying the kit to your user drumkit folder is also not a thing we do, since there could be easily a custom version of the kit using the same name which would be overwritten. In addition, the error would still be there in all following startups since the original kit was still not updated.

It might be annoying in your console but it does no harm. The kit you use within Hydrogen is already the upgraded one. It's more a decision for the Ubuntu package maintainers whether to pack and ship the original drumkits or to upgrade them themselves and ship their valid latest version.
