### ISSUE TITLE
Congratulations git clone 1.3.0-alpha-'d5339e034' 

### ISSUE THREAD

**Issue by UrbanDesimator** [hydrogen-music/hydrogen#1939]
Hydrogen version *          :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Just I have opted to do a git clone  @19:30pm UK Time 31.01.2024 As I spotted a lot of comits since 1.2.3 src release. Hydrogen shows 1.3.0-alpha-'d5339e034' Linux x86_64 Slackware64 Current, kernel-rt-devel-6.8-rc1-rt1 QT5-5.15.12_20240103: Built with alsa jack ladspa: lash=on lrdf=on cppunit=on portaudio=off potmidi=off pulseaudio=off debug=off.

My issue is :> Outstanding work since 1.2.2,  all the sample glitches/pops and  timing issues I had been having with 1.2.2 src release are gone.
I've had hydrogen playing a 16 bar song for 35 mins non stop no xruns, the odd glitches at the end of last bar returning to 1st are also gone.
I'm so happy IO'd gone back to 1.1.1 as that was last stable version.

I love the interface/ui improvements make a lot easier.
You all have done fantastic work and made a linux hydrogen user since very early of the start of the project. Congratulations 

please please please take an archive of my version and when you make significant changes do an A to B comparison on audio output and timing so it holds up. I've never heard audio sound so clear I've been on same hardware for 4 years plus so know it inside out.
UrbanMusic :-)))))))))

**Comment by UrbanDesimator** [comment]
I'm using using jack-1.9.22 with loop2jack on an amd fx4130  x86_64 8gb ddr3 with realtek ALC892 onboarrd snd card using snd-hda-intel driver and studio quality 2.1 desktop speakers & sub. GCC-13.2.0, clang-17, alsalib-1.2.11, alsaplugins-1.2.7.1, Xorg with xfce4-4.19.1, gforce gtx 660 Ti  nouveau driver

**Comment by theGreatWhiteShark** [comment]
Hey @UrbanDesimator ,

> I'm so happy IO'd gone back to 1.1.1 as that was last stable version.

Hydrogen's audio engine grew too naturally throughout the years and had some major design flaws causing long standing bugs and glitches. In order to fix all these I rewrote large parts of the audio engine. So, sorry for the troubles that caused and I'm glad things work smoothly again.

> Just I have opted to do a git clone https://github.com/19:30pm UK Time 31.01.2024 As I spotted a lot of comits since 1.2.3 src release. Hydrogen shows 1.3.0-alpha-'d5339e034' Linux x86_64 Slackware64 Current, kernel-rt-devel-6.8-rc1-rt1 QT5-5.15.12_20240103: Built with alsa jack ladspa: lash=on lrdf=on cppunit=on portaudio=off potmidi=off pulseaudio=off debug=off.
>
> My issue is :> Outstanding work since 1.2.2, all the sample glitches/pops and timing issues I had been having with 1.2.2 src release are gone.

Hmm. Most of those commits address changes for a new feature. All flaws in the audio engine I tried to to include in the 1.2.X releases as well. (It's always a tradeoff whether a change could cause trouble or not. So, it might be possible some commits fixing problems you faced did not end up in the 1.2.3 release). However, if you encounter glitches, pops, and timing issues in the 1.2.3 I consider all of them bugs and would like to fix them in a 1.2.4 patch release. No idea when 1.3.0 will be ready. So, it would be great if you could reproduce and file bug reports for them.

Also, you have to be careful with the songs and drumkits you save using version 1.3.0. I had to make some changes in the file structure. You won't be able to load them with any release earlier then 1.2.3.

**Comment by theGreatWhiteShark** [comment]
Again, in case you experience glitches, pops etc. in the last 1.2.X release: please report them back so I can fix them :)
