### ISSUE TITLE
Audio sounds duplicated after tempo change as transport slave

### ISSUE THREAD

**Issue by devloop0123** [hydrogen-music/hydrogen#1953]
Hydrogen version *          :1.2.3 and also 1.3.0-alpha both built from source
Operating system + version  : Linux Mint 21.3
Audio driver + version      : jackd2 1.9.20

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Running H2 as jack transport slave, MusE Sequencer as transport master, messes up H2 audio after tempo changes. Right after the first tempo change H2 audio sounds as if it's duplicated. So it sounds louder, as if the patterns are played doubly, but not exactly simultaneously: with a few milliseconds difference. 

On previous H2 versions the same audio glitch occurred when the transport master was looping. (So if that's been a familiar bug you know what it sounds like.)   

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by theGreatWhiteShark** [comment]
Hey @devloop0123 ,

Thanks for reporting!

I can reproduce the bug and take care of it.

**Comment by theGreatWhiteShark** [comment]
Hey @devloop0123 ,

Sorry for the long delay.

Could you use [this AppVeyor version of Hydrogen](https://ci.appveyor.com/api/buildjobs/4f2up333lywrqn7u/artifacts/Hydrogen-1.2.3-161-ge6dcdb30b-x86_64.AppImage) or compile the code in #1977 and check whether the sound and synchronization problems are gone?

Also, could you use the most recent [MusE](https://github.com/muse-sequencer/muse/releases/tag/latest) version as well? I had to fix something in there too.

Please note that the poor design of the JACK API leads to some UX drawbacks: In case you use `MusE` as timebase master, all relocations have to be done within MusE and _not_ Hydrogen. Otherwise, transport could get out of sync (when using tempo and measure changes).

**Comment by theGreatWhiteShark** [comment]
Awesome! Thanks for the quick response!
