### ISSUE TITLE
Selecting beats drag just draws beats?

### ISSUE THREAD

**Issue by bunglesss** [hydrogen-music/hydrogen#1966]
Hydrogen version *          : 1.2.3
Operating system + version  :  Fedora
Audio driver + version      :  Jack or Alsa

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Trying to select beats with the arrow instead of the pen from the toolbar, just draws notes. I used to be able to drag over them and copy and past patterns?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fedora RPM

Installed Packages
Name         : hydrogen
Version      : 1.2.3
Release      : 12.fc39
Architecture : x86_64
Size         : 19 M
Source       : hydrogen-1.2.3-12.fc39.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:ycollet:audinux

**Comment by bunglesss** [comment]
Oh, also the UI doesn't fully draw itself sometimes, I have to mouse over to unhide preferences, then go into that, then the whole UI redraws.
![Screenshot from 2024-04-20 15-52-35](https://github.com/hydrogen-music/hydrogen/assets/45080520/b9d57953-c4dd-4352-bd3d-2c52ecd17ad8)

**Comment by cme** [comment]
Oh boy, that's weird. Is this running on X11 or on Wayland, perhaps?

**Comment by bunglesss** [comment]
It will be Wayland I think Fedora defaulted to Wayland ages ago now. Weird indeed!

**Comment by cme** [comment]
> It will be Wayland I think Fedora defaulted to Wayland ages ago now. Weird indeed!

Did you have a previous Hydrogen working on the same system previously? Any idea which it was? I don't think there's been anything that's changed in Hydrogen itself that would cause this sort of behaviour. Perhaps other things (Qt version, wayland/Xwayland configuration or versions) changed along with the upgrade if it was installed by RPM. I'll see if I can set up a Fedora VM to attempt to reproduce.

**Comment by theGreatWhiteShark** [comment]
> Oh, also the UI doesn't fully draw itself sometimes, I have to mouse over to unhide preferences, then go into that, then the whole UI redraws.
Screenshot from 2024-04-20 15-52-35

Yeah. That definitely feels like a problem of a dependency/your system and not Hydrogen itself. Somethings like a wayland/Qt5/window manager mismatch. Or maybe your system is configured to discard window content above a certain threshold of resource consumption in order to free some. The parts visible are those frequently redrawn by Hydrogen.

> Source : hydrogen-1.2.3-12.fc39.src.rpm

I'm not a Fedora person. But the official repo still contains version 1.1.1 https://packages.fedoraproject.org/pkgs/hydrogen/hydrogen/. Did you maybe mix packages from different sources/repos?

Adding to Colin's suggestions you could also try the latest [AppImage](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.3/Hydrogen-1.2.3-x86_64.AppImage) release. This ships and uses its own Qt5 library. Maybe this already changes things at your end.

> Trying to select beats with the arrow instead of the pen from the toolbar, just draws notes. I used to be able to drag over them and copy and past patterns?

It draws multiple patterns? In case something is broken in Qt <-> Window manager communication on your system and mouse dragging can not be handled properly, it should only draw a single pattern. 

Are you able to drag select notes in the Pattern Editor? Is drag and drop of e.g. the instruments in the Pattern Editor working? 

As a workaround you can still select multiple patterns using <kbd>Shift</kbd> and arrow keys.

**Comment by bunglesss** [comment]
Yes I may need to roll back to the official Fedora package. The ycollet:audinux repo maintainer maybe needs to have a look. They have put loads of cool packages together for Fedora, so sure they'll have a look.

**Comment by bunglesss** [comment]
I wll try and explain better about dragging, so you layout your patterns at the bottom, then at the top you lay out the song from those patterns. I used to drag over, and copy and paste parts of the song, but dragging just draws more notes on this version.

**Comment by theGreatWhiteShark** [comment]
> Yes I may need to roll back to the official Fedora package. The ycollet:audinux repo maintainer maybe needs to have a look. They have put loads of cool packages together for Fedora, so sure they'll have a look.

This repo definitely seems to be worth the effort. 1.1.1 was released quite a while ago.

I just took a quick look at their [build log](https://download.copr.fedorainfracloud.org/results/ycollet/audinux/fedora-40-x86_64/07226250-hydrogen/builder-live.log.gz) and did not notice anything suspicious. Their Qt is quite cutting edge with version 5.15.12 (see https://code.qt.io/cgit/qt/qt5.git/log/?h=5.15). I'm on 5.15.8 locally. But I don't think this is the problem in here.

By the way, could you start Hydrogen in a terminal using `hydrogen -VDebug`, try to reproduce the described behavior (both blank window parts and dragging), and attach the output in here?

> I wll try and explain better about dragging, so you layout your patterns at the bottom, then at the top you lay out the song from those patterns. I used to drag over, and copy and paste parts of the song, but dragging just draws more notes on this version.

Just to be entirely sure: When the third button from the right in here http://hydrogen-music.org/documentation/manual/manual_en.html#chpt.song_editor.main_controls shows a cursor, you are not able to drag-select. Instead, it draws patterns (rectangles). And when clicking the button so it shows a pencil, it still draws patterns?

**Comment by bunglesss** [comment]
I tried this, no useful output on the command line. However, I was able to drag and copy and paste, I've no idea why that now suddenly works. I will keep playing about and see if it happens again and if there's a pattern.

**Comment by theGreatWhiteShark** [comment]
Hey @bunglesss ,

did the problem showed up again?

**Comment by bunglesss** [comment]
Hi, no it does seem to be okay now, not sure why though.
