### ISSUE TITLE
Cannot set non-integer tempo in the timeline editor

### ISSUE THREAD

**Issue by Naddiseo** [hydrogen-music/hydrogen#2007]
Hydrogen version *          : 1.2.0-beta
Operating system + version  : Ubuntu 24.04
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I have a song set at a tempo of 57.5, then I want to use the timeline editor to increase to 58, then back down to 57.5, however, the tempo editor part of the timeline rounds the tempo. Not such a big deal since I'm going to just set my base tempo to 57, but given the main tempo editor allows tempos at 2 decimal places, it would be nice for the precision to be maintained.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info > About' in the GUI or 'hydrogen -v' on the command line. Also, please indicate how you installed it, e.g. binary downloaded from SourceForge/Github, brew (macOS), OS repo (Linux), flathub (Linux), AppImage (Linux).
** if you are reporting a bug, please describe how the bug can be reproduced and add the corresponding [log messages](https://github.com/hydrogen-music/hydrogen/wiki/Accessing-log-messages-of-Hydrogen)

**Comment by theGreatWhiteShark** [comment]
Hey @Naddiseo ,

This issue is already fixed in the latest version of Hydrogen.

To work with a version more recent then what your distribution's repo provide, you have two options: use our [AppImage](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.3/Hydrogen-1.2.3-x86_64.AppImage) or [compile it yourself](https://github.com/hydrogen-music/hydrogen/blob/releases/1.2/INSTALL.md).
