### ISSUE TITLE
trigger instruments via midi doesnt work

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#234]
(tested with most recent code of today)

- connect a midi piano keyboard to hydrogen (only tested via virtual midi keyboard VMPK so far) 
- play notes on the keyboard

expected : the instruments in hydrogen are triggered
what really happens : i can hear sound from hydrogen but it's all chopped up and distorted

this does not happen with the official 0.9.6

can anyone reproduce this ?

**Comment by mauser** [comment]
Yes, i see the same..

**Comment by mauser** [comment]
... but it adds a nice effect :)

**Comment by mauser** [comment]
Normal "computer keyboard" is also not possible at the moment with the same problems.. but this is not so surprising since the code paths are similar.

@xjjx : Pawel, could have a look at this issue? It looks like the problems appeared after merging your latest fixes, at least i couldn't reproduce it with a version of prior to that.. At a closer look: i believe between b0c44a6c0b0e0691235f4ec611cbc56eba952757 and its succcessor.

**Comment by thijz** [comment]
hi @xjjx any update on this ?

grtz
Thijs

**Comment by xjjx** [comment]
For now I can confirm this issue. Give me time to the end of this week ... if I can't fix this you can hire some assassin ;-)

**Comment by thijz** [comment]
why would i spend money on an assassin ??  ....  if i can do it myself  ;-D
just wanted to check if you also saw the isse, didnt mean to push you.  take you time!

**Comment by xjjx** [comment]
Seems that my optimizations goes to far. Sorry about that. It's already fixed in main repo.

**Comment by thijz** [comment]
just tested and look OK :-)
will leave this ticket open for a couple days so i can test some more

thanks Pawel !
