### ISSUE TITLE
Pattern display showing incorrect number of bars / beats

### ISSUE THREAD

**Issue by Peregrino69** [hydrogen-music/hydrogen#257]
When I create a new pattern with size 4 and resolution 16 I get 2 bars with 4 beats each:
![hydrogen_wrong](https://cloud.githubusercontent.com/assets/10165090/7670116/a185bfbc-fc97-11e4-9e81-8d6ccdaea8d8.png)

What I expect to see is a pattern of 4 bars with 16 beats each:
![hydrogen_correct](https://cloud.githubusercontent.com/assets/10165090/7670128/72865040-fc98-11e4-8c04-c9b77bbfc725.png)

Same issue with 0.9.6 on Win 7 and 0.9.5/0.9.6 on Debian Wheezy.

**Comment by thijz** [comment]
this is an interesting ticket ...
i have no idea why it is the way it is
i guess i just got used to it, but indeed : it makes no sense

ideas anyone ?

**Comment by thijz** [comment]
i'm marking it as a bug since there doesnt seem to be a valid explanation for it
yesterday i was introducing hydrogen to a friend and he was very confused by it
i'm ok with it since i got used to it, but it just doesnt make any sense (especially for new users)

**Comment by pvint** [comment]
+1

**Comment by pvint** [comment]
I started taking a look at this tonight, but I don't want to take too much time at it until I found out the answer for one burning question, and maybe I'll direct this question towards @mauser : Is there a reason I don't understand for the current way this works? 

I've always found this confusing - when I set the "Size" to x, I get x/2 1/4 notes, and when I select y for resolution I get y/2 divisions on the scale. I would find it intuitive if "Size" was the number of notes shown, and resolution was the number of ticks across the entire scale. Sound correct?

**Comment by trebmuh** [comment]
I'd find it intuitive (as being a drummer/percussionist) if the **size** would define the number of bars and the **resolution** would define the number of sub-division of the bar. I've never understand how hydrogen was working here but somehow get used to it.

**Comment by pvint** [comment]
I agree, @trebmuh - Resolution would make the most sense to me as "per bar" as well. 
I took a bit of a look at this a few nights ago, but I must admit to having a bit of a time figuring out how it all works in the code. I'm close though, and I'll likely have another look over the weekend.

**Comment by trebmuh** [comment]
@pvint : please let me know if/when you need someone to test this. I'll be happy to do so.

**Comment by thijz** [comment]
i'm all for changing the time ruler to a more logical division as suggested by @trebmuh 
but i just cant help thinking 'there must have been a good reason to implement it the way it is now'

i'll post this on the dev list and see if we get an answer to this question

**Comment by trebmuh** [comment]
all good, let's see if there is a logical background for the way it's implemented the way it is now

**Comment by pvint** [comment]
I wasn't able to get any real time on this last weekend - maybe this weekend I'll do better.
I'll keep an eye on this thread here as well as the dev list for updated information/opinions.
@trebmuh - thanks for the testing offer, I'll keep that in mind!

**Comment by Shaac** [comment]
So I was writing these comment on how this makes no sense, but by explaining myself I found the reason why the current implement is logical in a way. Note that is way not intuitive at all.

I believe that the meaning of “16“ is [sixteenth note](https://en.wikipedia.org/wiki/Sixteenth_note). The Wikipedia page list the translation of the US word into many languages, and it contains the world “16“ in only a few of them. For me, being French, a sixteenth note is not at all related to the number 16 whatsoever, more related to the number 4, as it is defined as a forth of a beat. If you ask me, the name “sixteenth note” is not well chosen because it has meaning only for a 4 beats measure. Anyway, with this in mind, Hydrogen makes perfect sense.

So, a suggestion is to write the actual name “sixteenth word” in the drop down list, in parenthesis beside the number or something like that. That way in it clear what 16 means. And it can be translated, so that the user may understand this technical word.

**Comment by Shaac** [comment]
Ok so I misunderstood the ticket. What I said above is not very relevant.

About the current behavior, so no one has any idea why `size` is not the number of bars as stated in the manual, but actually twice the number of beats…

About the proposed solution in the screenshot of the first post, I find it problematic. If `size` 4, and `resolution` 16 mean “a pattern of 4 bars with 16 beats each”, then we force the user to use 4 beats long bars. Size 1 and resolution 4 means four fourth-notes. But how do I represent a 2/4 bar? Or a 7/4? With the current system it is respectively size 4 and size 14 (which whatever resolution we want).

Resolution should be independent of size. So size should by itself express any length of a bar. Or an other parameter named “beats” should be introduced.

But I talk a lot not knowing a lot about this. We should, as hinted by @Peregrino69 look at how it is done elsewhere, to make the less confusing interface.

PS: I note that the first sentence of the ticket is incorrect:

> When I create a new pattern with size 4 and resolution 16 I get 2 bars with 4 beats each

 These are not 2 bars with 4 beats, but 2 beats with the emplacement of the sixteenth notes.

**Comment by Peregrino69** [comment]
"Resolution should be independent of size"

Absolutely. The optimal solution would be size to set the number of bars, standard notation (i.e. 4/4; 12/8 etc.) to set the beat and resolution to determine what is the, well, resolution you want to insert the hits int. For example setting size 4, beat 3/4 and resolution 8 would give you 4 bars of waltz where you can enter 8th notes. Increasing resolution to 16 would let you enter 16th notes etc.

**Comment by trebmuh** [comment]
I'd love to see this one nailed down since it's really confusing especially for a new comer :)

**Comment by thijz** [comment]
IMHO this is a big one that really is a core parameter of hydrogen (or any sequencer really)

refering to the post by @trebmuh : 
_"size would define the number of bars and the resolution would define the number of sub-division of the bar"_

1) is this statement something that everyone agrees to ?
2) the 'fix' for this would be a GUI change only, right ?  I mean this doesnt impact songs created prior to this fix ?

**Comment by Peregrino69** [comment]
So Size 4 Resolution 16 would give me 4 bars with sixteenth-notes? I'm in. 

As I suggested above, a real beat counter (3/4, 4/4, 12/8 etc.) would also be useful. Awesome if it could be applied per pattern... so in the middle of a 6/4 tune I could slice in the odd 5/4 bar... I do believe that'd require a bit more than just a GUI change, right?

**Comment by pvint** [comment]
> size would define the number of bars and the resolution would define the number of sub-division of the bar

This makes sense to me.

As for it "just being a GUI change" - I think technically this is true, however having looked at this in the past unless you are simply changing the labels on the GUI, it would be quite a substantial change. It has been a few months since I looked at this, but when I was looking at changing this I found that any change is likely going to require making many changes in different parts of the code. 

I think @Shaac expressed it well above, in that we need to define clearly what is *desired* for this, and to do that we should take a good look at how other applications handle this. If there is a standard, we should go with that, IMO. If they are all different, we need to decide on a system that makes sense for Hydrogen and its users. 

This conversation has been going on for quite some time now, and one thing is jumping out at me: Nobody seems to understand why it is set up the way it is currently (or at least nobody has spoken up about it). I feel this is confusing for new and old users alike, and I would love to see this done. Winter is coming soon here, which gives me more free time for projects, so I may be able to take this, however we need a clear definition of what we want. as @thijz said above, this should not impact previous songs.

Side note (trying to stay on topic!): @Peregrino69  The beat counter showing 3/4 or 4/4 etc is a great idea, and while it is related that likely should be handled in a separate request to keep things straight. (read: My suggestion is to make that request! :) )

Paul

**Comment by pvint** [comment]
I made a change that makes sense to me - "Size" is number of bars, and "Resolution" is number of 1/4 notes per bar.
Just as a "proof of concept" really so far since I am exploring other ideas and this is *not* tested yet for backwards/forwards compatibility (or for anything really!). But have a look at https://github.com/pvint/hydrogen/tree/beats_res_257 and see if this makes sense to you.

Thanks!
Paul

**Comment by pvint** [comment]
Screenshot: 
![snapshot31](https://cloud.githubusercontent.com/assets/608740/20459157/d33ff4f4-ae85-11e6-9d02-d1e98650cfb3.png)

**Comment by pvint** [comment]
Also thinking this might be a bit more intuitive (mockup):
![snapshot31](https://cloud.githubusercontent.com/assets/608740/20459195/035f9c10-ae87-11e6-8a1f-cb41789a3df8.png)

**Comment by Peregrino69** [comment]
Haven't checked this for a while... 

@pvint, that's exactly what I'm talking about. Size = size of the pattern in bars, resolution = number of notes in a bar. Or as @trebmuh put it, number of sub-divisions per bar. The second screenshot is indeed more intuitive as with size 4, notes 1/16 I know I have 4 bars where I can insert sixteenth-notes - however I'd keep "Resolution" as that's (at least in my experience) the most common term for this. 4 bars, resolution 1/16 - clearer than 4 bars, resolution 16. 

But that brings up @Shaac's point. This way Hydrogen is tied to strict four-beat. There's no way to make a walz or 5/4 pattern, so BeatCounter comes into play. I admit I never read that part of the manual - hey I'm an engineer, we don't read manuals :-D 

Actually I skimmed through it, read "tap tempo with steroids" and "suppose you have a live band"... I've not considered using Hydrogen with a band so didn't pay so much attention. And haven't looked at the BC since. I re-read the manual, and I have an idea how to enhance the BC. As suggested I'll submit that separately :-)

BTW I don't know what exactly you've done, but 0.9.7 seems to be much more responsive than 0.9.6, Big thank you to the whole team :-)

**Comment by trebmuh** [comment]
Hi all.
@pvint : could you tell me if those strings (Resolution: "4", "8", "16", "32", "4T", "8T", "16T", "32T", and "off") are translatable? I've had a quick look to the French translation file, and it doesn't it seems. Am I wrong here?
I'd like to translate these in French since 1/4, 1/8, 1/16, 1/32 ... doesn't make any sense in French (should be "noire", "croche", "double-croche" and "triple-croche").

**Comment by pvint** [comment]
I verified, and no they are not currently translatable. Making it so is definitely something to consider while making other changes there. One problem we will run into is having much space for text in the menu. Do these abbreviate well?

**Comment by trebmuh** [comment]
@pvint : if possible, I'd prefer to keep them un-abbreviated but I can try to find some clever abbreviation. To be sure to understand, are you meaning the text *in* the menu, or the text of the current selection (clear-blue background) ?

**Comment by jeremyz** [comment]
Hey, I just read it all and had a look at @pvint 's branch.
It works well, makes sense, and as for backward compatibility,
you'll have hire res that you used to when you load on old pattern (not over 64) that's it.
This should be merged !!!

**Comment by trebmuh** [comment]
@pvint is this on a good enough shape to make a PR against master maybe? It would be great to have it included for 1.0.0 !

**Comment by pvint** [comment]
@trebmuh   To be honest I barely remember doing it... I will have a look tonight :)

**Comment by pvint** [comment]
@trebmuh  I just gave it a quick test, and it is nowhere near ready. It seems I only had the basics done and there's definitely some gui stuff to do. Also, if memory serves this change goes all over the code.. might take some time. I'll try to stay on it.

**Comment by pvint** [comment]
Actually - disregard my comment above. Just a couple little things to verify and I think it's OK

**Comment by trebmuh** [comment]
@pvint nice to read! Please let me know (ping me) when there is a PR ready to be tested.

**Comment by pvint** [comment]
On hold until #538 is resolved.

**Comment by trebmuh** [comment]
OK, fair enough :)

**Comment by jeremyz** [comment]
hello @pvint, I worked on #538 cause I wanted this to move forward ;))))

**Comment by pvint** [comment]
and it was very much appreciated @jeremyz ! 
I will try to get back at this over the next couple days ))

**Comment by mikotoiii** [comment]
Development has not stopped, we're just having issues with our website. It's been down for several weeks, and currently there is no ETA on when it will be back online.

**Comment by cme** [comment]
#999 should address this sufficiently! :)

**Comment by cme** [comment]
Closing as #999 is commited on main :)
