### ISSUE TITLE
Hydrogen can't export library

### ISSUE THREAD

**Issue by PostPollux** [hydrogen-music/hydrogen#262]
Hi. First of all thank you for such a great software. I discovered it a few days ago. It's awesome!
Now to the problem:

I started to creat an own library, but for some reason I'm not able to export it. :( 
When I hit export there is a console window flashing up for a fraction of a second and then it says "drumkit exportet". but there is no file exportet.
I managed to make a screenshot of the console:
![exportlibrarybug](https://cloud.githubusercontent.com/assets/9008901/8159370/43c0e2fe-1366-11e5-833f-44d84d497784.jpg)

Any idea how to fix this problem?
thanks,
Johannes

My system:
Windows 7 64 bit
7-zip 9.20
Hydrogen 0.9.6-alpha1 snapshot of February 2011

P.S.: February 2011... it's been quite a while. Do you actually intend to release a new version in the near future? Would be really a pity if this awesome software stops getting even better!

**Comment by mauser** [comment]
Hi Johannes! 
Unfortunately, this bug is a known limitation of the windows version.. the export depends on a command which is only available for linux systems. 

The problem is not that the development of Hydrogen stopped, there are much newer versions available for Linux.  We just never provided an updated release for Windows... But there is a good change that there will be an updated Windows Version in the Future, since someone from the community is currently working on a new build script for the Hydrogen windows version.
