### ISSUE TITLE
importing drumkits sometimes fails

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#269]
when i try to import a drumkit (from the server) the progress bar in the popup stops just before 100% and hangs
if i close that popup i sometimes get a message that the drumkit was installed, or sometimes it just fails

starting hydrogen from cli shows this after i close the popup

(E) Download::__http_request_finished Error: Request aborted
(E) Download::__fetch_done Error retrieving the resource.
(E) Drumkit::install archive_read_open_file() [2] Failed to open '/tmp/Roland_MC-307_TR-909.h2drumkit'

when i run hydrogen with the -Vdebug option installing drumkits seems to work just fine ...

**Comment by mauser** [comment]
Hi Thijs, 

this is not a hydrogen problem (in my opinion).. There has been a problem with the connection and the http request has been aborted. This is nothing we can do about..

**Comment by mauser** [comment]
Can we close this ticket? Or does the problem still persist?

**Comment by mauser** [comment]
Hi,

i was just rewriting the DownloadWidget for QT5 and ran into the same behaviour during some tests. It turned out that in the failing cases, SourceForge redirects to a wrong url. Example: SF tells H2 that a soundlibrary is now located at http://netassist.dl.sourceforge.net/project/hydrogen/Sound%20Libraries/Main%20sound%20libraries/deathmetal-drumkit.h2drumkit. The download fails, checking the URL with wget gives a 404. Downloading again, SF redirects now to http://netcologne.dl.sourceforge.net/project/hydrogen/Sound%20Libraries/Main%20sound%20libraries/deathmetal-drumkit.h2drumkit and everything works.

So this seems to be more a problem with SourceForge, not with our client.
