### ISSUE TITLE
Ctrl-S doesnt work when the focus is not on the main window

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#287]
yesterday i was working on a song (during rehersal) and i was tweaking some stuff in the mixer window
when i finished tweaking (still in the mixer window) i hit Ctrl-S to save the song, closed the mixer window and loaded an other song

later i went back to the first song, i saw that all the tweaks i did were gone :-(

seems that Crtl-S doesn work when you are working in the mixer window

**Comment by mauser** [comment]
That's the default behaviour of nearly all applications. You're interacting with the window in the foreground, which has its own key bindings.

**Comment by thijz** [comment]
ok, i get that ... i guess
but, but, but ... 
ok i guess you are right

**Comment by Gimmeapill** [comment]
Actually there is a usability issue here, but it has nothing to do with keyboard focus (I also lost data once by closing too fast).
What I think Hydrogen is missing here is the popup warning saying: "the current project has some unsaved data would you like to save it now? Yes/No/Cancel".
Most software has such a safety feature nowadays (ardour, lmms, renoise to name a few), and it is certainly a disconcerting behavior for new users, not sure if it was omitted by design.

**Comment by thijz** [comment]
i will create a separate ticket for this 'ask to save before close' issue
