### ISSUE TITLE
Issue with importing drumkit (1/2)

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#298]
I've been downloading all the drumkits available today and found out 2 issues. This is the first one. (Debian 8 Jessie updated - Hydrogen from https://github.com/hydrogen-music/hydrogen/commit/eed4d32b7a0313a72836915467c514841c508ea6 )

Some of the drumkits are downloaded and working when playing with, but they still appear not installed.
![hydrogen bug drumkit 1](https://cloud.githubusercontent.com/assets/8705846/9972121/cabc824a-5e61-11e5-9138-6fb389a3e4b6.png)

This is the case for the following drumkits: “Death Metal”, “Boss DR-110 (sf)”, “circAfrique v4”, “BJA_Pacific”, “rumpf_kit_z01_gm”, “belofilm.com - AC-Guitar-Strums (flac)” and “Denon CRB-90”

**Comment by thijz** [comment]
related to #269 ?

**Comment by thijz** [comment]
i can reproduce this with todays code (ad9dfa9)
drumkit circAfrique is installed but status stays 'new'
removing the drumkit and reinstalling does not help

**Comment by trebmuh** [comment]
Hi @thijz , did you try with the other drumkits I mentioned above as well ? ( “Death Metal”, “Boss DR-110 (sf)”, “circAfrique v4”, “BJA_Pacific”, “rumpf_kit_z01_gm”, “belofilm.com - AC-Guitar-Strums (flac)” and “Denon CRB-90” )
Just trying to have a consistent report here.

**Comment by mauser** [comment]
Hi,

this is an old issue and has to do with the packaging of the drumkits. The name of the folder in the package has to match the name of the drumkit - otherwise hydrogen is not able to check if the kit is already installed. Those drumkits need to be edited and re-uploaded. And i'm not sure if the blanks in the filename are working..

**Comment by trebmuh** [comment]
Trying helping going further, here is the list of the incriminated drumkits, their folder name and a comment
kit name | folder  name | comment
------------ | ------------- | -------------
Death Metal | DeathMetal | missing space character
Boss DR-110 (sf) | Boss DR-110 | missing "(sf)" characters
circAfrique v4 | circAfrique v4 | I cant' see any differnece here
BJA_Pacific | BJA_Pacific | I cant' see any difference here
rumpf_kit_z01_gm | rumpf_kit_z01_h2 | difference between "gm" and "h2"
belofilm.com - AC-Guitar-Strums (flac) | belofilms.com - AC-Guitar-Strums (flac) | Note the "s" character at the end of "belofilm" in the folder name
Denon CRB-90 | Denon CRB-90 | I can't see any difference here

@mauser : firstly, could you please suggest a way for me to help debugging further ?
secondly, thinking more on a long term way, wouldn't it be a good idea to "enforce" (in a coding way) the kit name and the folder name to be the same if a mismatch between those two would be the cause for some failing ?

**Comment by thijz** [comment]
+1  for enforcing kit name = folder name

**Comment by mauser** [comment]
About BJA_Pacific and circAfrique v4: the path which is listed in the drumkits_list.php is wrong (http://sourceforge.net/projects/hydrogen/files/Sound%20Libraries/Main%20sound%20libraries/BJA_Pacific.h2drumkit/download), it should not have the /download extension since we analyse the URL to retrieve the drumkit name.

**Comment by trebmuh** [comment]
I had a look at that and I came to the conclusion that the http://hydrogen-music.org/feeds/drumkit_list.php is somehow hand-written and would need someone with write-access to hydrogen-music.com to achieve the change. I'm not sure who is the boss (or who are the bosses) for here. Please, denounce yourself :)

**Comment by mauser** [comment]
Hi! 

I have access to the server and i'm already working on the fixes..

**Comment by trebmuh** [comment]
Awesome, thanks for that @mauser 
Let me know when you're done with that and I can test from here.

**Comment by trebmuh** [comment]
BJA_Pacific is correctly reporting itself as "installed" now. Thanks mauser :sunglasses:

**Comment by trebmuh** [comment]
Any way I could be of any help improving the situation here ?

**Comment by pvint** [comment]
There's been some discussion of this over on issue [issue 212](https://github.com/hydrogen-music/hydrogen/issues/212 ) about this... I had set up a temp drumkit server and repackaged some of the kits so that the .h2drumkit names matched the directory names inside the tarball, and we ran into some issues when a kit is installed and the updated version gets installed, either the kit is listed twice or there are file collisions and errors.

A way to avoid this for users might simply to give the new package a new unique name (and matching directory name). On that note I was thiking that maybe the Export function should sanitize the name (convert spaces to underscore and removing special chars like "&*()" etc). 

I'll volunteer to take this if you want.

**Comment by mauser** [comment]
Hi,

i've spend some time this week on editing our drumkits list, fixing url's  and repairing drumkit names, mostly for the kits from the drumkit contest. Now all kits should show up as "installed" after downloading them... As paul already stated, it might be that some drumkits are now showing up two times in your local soundlibrary (not in the soundlibrary import dialog). If i remember correctly, then this will be only the case for the belofilms guitar strums kit.

**Comment by trebmuh** [comment]
Hi @mauser and thanks for that. I can confirm that now, only the "belofilms" drumkit is downloaded but it still show "new" (and not "installed").

There are a few drumkits that are unable to be installed:

![hydro-denoncrb90](https://cloud.githubusercontent.com/assets/8705846/23362624/f47a62b6-fcf6-11e6-8259-4a74435accb9.png)
![hydro-rumpfkitz01gm](https://cloud.githubusercontent.com/assets/8705846/23362626/f483399a-fcf6-11e6-8b1d-fd07c24e32d5.png)
![hydro-circafriquev4](https://cloud.githubusercontent.com/assets/8705846/23362627/f489a79e-fcf6-11e6-9cbe-106629cc0ef0.png)
![hydro-k27trashkit](https://cloud.githubusercontent.com/assets/8705846/23362628/f4915462-fcf6-11e6-95a5-0c15df81461f.png)
![hydro-deathmetal](https://cloud.githubusercontent.com/assets/8705846/23362629/f49cd95e-fcf6-11e6-92f5-f2b17a525ac3.png)

Hope that helps.
