### ISSUE TITLE
Director: Editing Issues

### ISSUE THREAD

**Issue by Pinecone1200** [hydrogen-music/hydrogen#30]
I have recently started using Director extensively to add lyrics / chord notifications.  It is a great way to to both learn a song and also ensure that I have the song structure on Hydrogen nailed.

What have noticed is that if I move a comment from one line to another in the Director tab, I am ending up with duplicate lines.

The move appears to work and leave the source line blank,  however on reopening Director I find that the original line still has its content and I have to enter blanks in order to ensure the deletion works.

Director is already a really useful feature but this editing issue makes it painful to use.

**Comment by thijz** [comment]
just retested with todays github code > issue still present

**Comment by jduemes** [comment]
It would be a a very good thing to make it behave like a spreadsheet column, or something near that. It would also be good to have Ctrl+X/Ctrl+C/Ctrl+V work too.
H2 Version: 0.9.7-'c8e6a9a'

**Comment by trebmuh** [comment]
+1 with the just-above comment.

Also, trying this with a GIT build from today (ie: https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18), I can confirm that this bug is still here. The easy-to-find workaround is to delete the non-desired comment.

Hope that helps
