### ISSUE TITLE
Glitchy/distorted audio at 48kHz- Hydrogen 0.9.7

### ISSUE THREAD

**Issue by chrisbeckstrom** [hydrogen-music/hydrogen#315]
Was super frustrated that Hydrogen didn't 'remember' to create per-instrument tracks and discovered the 0.9.7 version fixed that bug. I installed 0.9.7 using a deb from https://launchpad.net/~blablack/+archive/ubuntu/music-prod/+build/8106534

Now Hydrogen (mostly) remembers to create per-instrument tracks, but the audio that comes out is choppy and distorted, sort of as if there's something wrong with the sample rate. This issue does not happen when JACK is set to use 44.1khz as a sampling rate. I am not seeing xruns happen during the distortion.

I've tried setting the buffer size in Cadence/JACK and Hydrogen to various numbers, but whenever JACK is running at 48kHz I hear the distortion. Perhaps there is another way to get 0.9.7?

Thanks for creating such a fantastic instrument!

Info about my setup:
KXStudio (Ubuntu 14.04.3 LTS)
Running Cadence, JACK, Catia
Audio interface: M-Audio FastTrack

**Comment by thijz** [comment]
this only happens when using 'per instrument' outputs, or also when using just 1 output ?
what audio engine is selected ? (Tools - Preferences - Audio System) jack or auto ?

i have tried to reproduce this with several jack settings, but i never heard any distortion ...


configuring your system to build hydrogen yourself isnt hard at all
you can find info here : https://github.com/hydrogen-music/hydrogen/wiki/Building-Hydrogen-from-source-(LINUX)

**Comment by chrisbeckstrom** [comment]
thanks for the reply! I believe the issue was happening with both 'per instrument' outputs as well as 1 (stereo) output. The audio engine is JACK

I'm starting to get a bit more comfortable building stuff from source.. maybe I'll try that!

**Comment by blablack** [comment]
@chrisbeckstrom did you manage to troubleshoot this issue?
I'm having the same here, although I don't see any improvements when changing the sample rate in Jack...

**Comment by mauser** [comment]
Hi! 
Is this still a problem for you or was it solved with using hydrogen 0.9.7 ?

**Comment by mauser** [comment]
Closed due to lack of feedback..
