### ISSUE TITLE
Official web site does not mention/link to latest releases

### ISSUE THREAD

**Issue by dreaming-augustin** [hydrogen-music/hydrogen#347]
I am trying to upgrade the gentoo ebuild from 0.9.5 to the latest stable release.

The official website only mentions a stable release for 0.9.5:
http://www.hydrogen-music.org/hcms/node/21 

The news item "Hydrogen 0.9.6 released"
http://www.hydrogen-music.org/hcms/node/13054 
mentions:
"The release can be downloaded via github: https://github.com/hydrogen-music/hydrogen/archive/0.9.6.tar.gz"

After a long while spent searching, I finally found the list of latest releases here:
https://github.com/hydrogen-music/hydrogen/releases 
which include 0.9.6.1 and 0.9.7-beta1 not mentioned elsewhere.

Maybe the official web site should be updated so as to point users/developers to github and the list of releases there...

**Comment by trebmuh** [comment]
Good summary @dreaming-augustin . I'm adding a +1 on this.

**Comment by mikotoiii** [comment]
I believe that Thjis looks after most of the website probably in
conjunction with mauser. If it's needed and or wanted, I can probably help
out with updating and maintaining some of the site. I'm familiar with
drupal (which is what I believe the backend is from thjis's post a while
back about ways to contribute) and know enough php to get by on any of the
sites i've needed to work on.

Failing that I can have a look next week and see if I can't compile a list
of updated download links to send to the devel list for updating the site.
Since 0.9.5 is still in use in some distros, it might be good to go that
far back. I suppose the alternative would be to start looking to create
packages for those distros to update to 0.9.6

I've also been wondering for a while now whether I should start
investigating doing a back port of my windows cross compilation scripts to
0.9.6 so we can get a final Windows release out as well. I know this last
part is a little off the original topic, but figured that it fit in well
enough that I might as well ask. I can create a seperate ticket for the
Windows thing if need be.

**Comment by mauser** [comment]
Hi everyone! 

Thanks for bringing this up, @dreaming-augustin. The main problem is that the website/forum is more or less unmaintained at the moment and the content is clearly outdated. 

I thought about switching back to a more or less static site (which could be developed via git), like the we one we had before switching to drupal. So plain html/css/php with no fat content management. This is why i would like to avoid more update/maintainance work at the moment. 

@mikotoiii, maybe we can collobarate with creating the new site? 

I suppose that most distrutions offer now packages for 0.9.5, so those could be taken from the site for sure.

**Comment by mikotoiii** [comment]
Sounds good to me @Mauser. If you want to shoot me an email, we can get
started whenever you have time. Boyer.steve@gmail.com

**Comment by mauser** [comment]
Hi,

i've updated the downloads page yesterday and deleted some older links (packages are still to be found on sourceforge).

**Comment by trebmuh** [comment]
@mauser the Windows link to the 0.9.7beta2 on https://github.com/hydrogen-music/hydrogen/issues/347 point to "http://www.hydrogen-music.org/hcms/node/%20%20https://sourceforge.net/projects/hydrogen/files/Hydrogen/0.9.7%20Binaries/Hydrogen-0.9.7-beta2-win32.exe/download". I'm pretty sure the first part is non needed :)

**Comment by trebmuh** [comment]
Been reported here as well: http://hydrogen.popez.org/hcms/node/16881

**Comment by mauser** [comment]
Thanks, fixed!

**Comment by trebmuh** [comment]
Yes it does, thanks @mauser !
