### ISSUE TITLE
Exporting Song Fails

### ISSUE THREAD

**Issue by davidpetersonharvey** [hydrogen-music/hydrogen#367]
Ubuntu Studio 14.04 on Acer Aspire with 4GB RAM

Exporting to individual tracks; last track fails. 

Exporting to single track; fails.

In both cases, the last track to write will show progress to 100%, then it will hang and no track will be written.

**Comment by trebmuh** [comment]
which hydrogen version @davidpetersonharvey ?

**Comment by davidpetersonharvey** [comment]
Sorry, forgot to include, .96 Beta
How can I downgrade to a stable version? 
Love the package! Graaf work! 

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 1, 2016 at 7:10 AM, Olivier Humbert<notifications@github.com> wrote:   
which hydrogen version @davidpetersonharvey ?

**Comment by mauser** [comment]
@davidpetersonharvey : You could try to use build hydrogen 0.9.7-beta2 from source. Apart from that, the [kxstudio](http://kxstudio.linuxaudio.org/Repositories) repositories have often recent version of hydrogen (you have to check if they still support 14.04).

**Comment by trebmuh** [comment]
@davidpetersonharvey: another thing you can do in order to try to get some more information is:

1. starting hydrogen from a terminal,
2. exporting a track the way it fail,
3. looking in the terminal if something is written,
4. reporting what's written in the terminal (if so) here.

Hope that helps.
