### ISSUE TITLE
Clock does not work when using jack driver

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#369]
The clock stays always at 00:00:00 when using the jack driver.  Apart from that, the song plays fine.

**Comment by xjjx** [comment]
The problem is that hydrogen->getHumantimeFrames method always return 0. This broke also entire JackTransport in Master mode. I made git bisect and seems that problem is in that commit:
fa58843f7a7ed51c831ccba6da66b3d24ca7652c

... but .. I didn't make all this changes ! For example it shows that this commit made change in .gitignore file which is not true. So before I try to fix this issue , I need to understood what happened there ?
I'm afraid that there could be more issues related to this commit :(
@mauser can you help me with this ?

**Comment by mauser** [comment]
Sure! At least i can try..  Seems to be that (at least a part of a problem) is that this commit removed the call to setHumantimeFrames in jack_output.cpp .

The whole commit seems to be a merge commit - so i suspect that you pulled the latest version of hydrogen from our git repository and merged it:

> commit fa58843f7a7ed51c831ccba6da66b3d24ca7652c
> Merge: 499f26e 0dbda89
> Author: XJ <xj@wp.pl>
> Date:   Sat Feb 14 01:55:52 2015 +0100
> 
> Sync to upstream

Maybe there has been some kind of merge conflict which had to be resolved manually? If i see it correctly, then in 499f26e as well as 0dbda89 the call to the setHumantimeFrames is present, but not after the merge (i've just did a checkout of both commits and grep'ed for setHumantimeFrames).
Quite confusing :-/ And strange that nobody noticed that the Jack transport is broken in such a long time

**Comment by xjjx** [comment]
Thanks. Yes, there was conflict with this commit 95e954376fc4739ec1645264ab39257dadd39a73. Actually there was a lot of conflicts during this pull request, so I did my best to resolve all of them but seems that was not enough. I'll try to fix JackTransport and this issue and test it a little.

**Comment by mauser** [comment]
Thanks, the clock seems to work fine now!
