### ISSUE TITLE
Hydrogen for Windows is fat

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#376]
Hydrogen for Windows is a 57,9 MB install. Inside installation directory, there are two sets of executable files, one in "root" dir, another in `bin` subdirectory. Each `hydrogen.exe` file is 60 MB, which is quite a lot for a dynamically-linked executable. Last, there's `lib` subdirectory with `libhydrogen-core-0.9.7.dll.a` static library, which is, in my opinion, not really needed in binary package.

**Comment by elpescado** [comment]
As a comparison, hydrogen binary on OSX is about 3,5 MB.

**Comment by mikotoiii** [comment]
bin and lib should be able to be trimmed, I don't think that they're required. As for trimming the fat on the executable, I'll have to look at how mxe is compiling it, there might be some things in cmake that we can turn off.

I wanted to do a scratch build for Windows soon anyway to check the mxe stuff, and see if there's a way I can make the script a little better, so i'll start looking into this.

**Comment by elpescado** [comment]
`strip` may help reduce size of executable.

**Comment by mauser** [comment]
Hi,

i've started to look into this issue. In addition to the issues brought up by @elpescado, i'm considering to remove the jack and ladspa installers from the exe. Or providing a second setup which contains the additional installers.. I'm not sure how many people are really using those installers, especially since LADSPA support is currently not working in hydrogen for windows.

After removing those installers and stripping all binaries, the binary was ~35MB without further optimization.

**Comment by mikotoiii** [comment]
Sounds good to me. We can always put a sticky in the forum, or a link to
jack on the webpage.

As for the ladspa plugins, i haven't had much time lately to look at it,
but if it's just not including it in the build script. We might be able to
set a variable and force it. I'm hoping to have a bit of free time to start
looking into that issue here soon.

**Comment by mauser** [comment]
@mikotoiii : I think i have LADSPA already working now, at least compilation succeeds and LADSPA is enabled. Clicking on the FX buttons brings up the Plugin browser, so this seems to be fine for the start.

 I'll have to lookup in the code where those plugins have to be placed.. at the moment none is found on my system.

The solution for enabling it in the build process was easy, just copied the LADSPA header to the appropriate mingw-include directory in /opt/mxe. I suppose this step is missing in the mxe installation process.

**Comment by mauser** [comment]
Just for the record: Setting the LADSPA_PATH environment variable did the trick..

**Comment by mauser** [comment]
Btw, when using a release build (WANT_DEBUG=false) i can get as low as 22mb. This sounds much better then the initial 57mb..

**Comment by mikotoiii** [comment]
Setting the LADSPA_PATH in Windows? We should probably add that step into
the build script and document it in the readme.md file. I remember seeing
something about needing to copy the plugins into a specific directory for
audacity.

If we're going to remove the jack installer, we should probably also update
the installation instructions to include that.

It might be a good idea to create a page for the website refresh that
contains clear cut installation instructions for Linux, Mac, and Windows.
It can also have the optional stuff like a link to jack and the ladspa
plugins, and other related things that we want.

**Comment by mikotoiii** [comment]
The core issue of this ticket was solved in your update to the scripts mauser, we can probably close this and refer back to it for the new website if we need to.

**Comment by mauser** [comment]
Ok, i'm closing this ticket now..
