### ISSUE TITLE
initial 'warning you are using a dev version ...' popup keeps popping up

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#387]
whenever i start hydrogen this window keeps popping up (version built with todays code)
it doesnt matter if i hit ok or 'dont show any more'

![image](https://cloud.githubusercontent.com/assets/1384210/16886953/69798542-4ad7-11e6-94d4-6b8b5479a586.png)

**Comment by pvint** [comment]
Hi Thijs!

I have seen this before - note that the " don't show again "  only gets
saved if hydrogen exits normally. If it crashes or you ctrl-c it it will
not save the setting

Paul

**Comment by thijz** [comment]
hi Paul
i just noticed that it is a permission issue:
i built hydrogen under /usr/src/hydrogen using root privileges and run it as my own user
when i try to import a drumkit (from the drumkit repo) i get this in the terminal : 
(E) SoundLibraryImportDialog::writeCachedData Failed to open file for writing repository cache.

so i tried running it as root and the import drumkits was ok + i no longer get the initial warning message

i used to build hydrogen in some dir in my /home but i wanted to do it the 'proper' way 
guess i'm missing something basic here ?

grtz
Thijs

**Comment by pvint** [comment]
I usually keep my sources under use/local/SRC which I give a group rw
access to and include my user in that group. Works well for me.

**Comment by thijz** [comment]
guess i'll have to do something like that
closing ticket now

thanks for the quick feedback !

**Comment by thijz** [comment]
actually, i'll reopen it  :-)
since this is the procedure described in the wiki, i wont be the only one that runs into this issue

so what would be the cleanest way to fix this ?
- update the wiki and change the build directory ?
- chown the /usr/src/hydrogen dir ?
- something else ?

**Comment by pvint** [comment]
I would maybe suggest changing the wiki so it is not so specific... Maybe
"unpack the source in a directory owned by your user" and let the user
decide where they want it

On Jul 15, 2016 16:24, "thijs" <notifications@github.com> wrote:

Reopened #387 <https://github.com/hydrogen-music/hydrogen/issues/387>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/hydrogen-music/hydrogen/issues/387#event-724859423>,
or mute
the thread

**Comment by thijz** [comment]
ok, good suggestion Paul
made the wiki text more generic
