### ISSUE TITLE
Alt + P shortcut to the Preferences dialog is currently broken

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#393]
When on Hydrogen main's window, if I'm trying to make the Preferences dialog to pop up using Alt + P, it does not work since Alt+P is opening the sub-menu "Project".

Edit: when running from a terminal, I've got this message appearing when doing a first Alt + P: 
> QAction::eventFilter: Ambiguous shortcut overload: Alt+P

The second Alt + P is opening the sub-menu "Project".

**Comment by mauser** [comment]
Hi! 

Confirmed. 

Since Alt+P seems to be quite common for "Preferences", i would like to stick with that. But this means that we have to change the short cut for the "Project" menu. Alt+J would be possible. 

The downside is that the keyboard shortcut is related to the translation of the string: The string of the "Project" menu entry is "&Project", which is different from "Pro&ject". This means that this string has to be re-translated in all translations. I suspect that not all translations will be updated for 0.9.7, so in the end a lot of people will end up with an untranslated text for the Project menu. But i suppose that's the only reasonable solution at this point..

**Comment by trebmuh** [comment]
> But i suppose that's the only reasonable solution at this point..

I suppose too since I can't find a solution allowing to workaround that. Maybe we could send an email to the different translators before releasing, asking for a special effort on this specific line of translation?

**Comment by mauser** [comment]
Should be fixed now..

**Comment by trebmuh** [comment]
Fresh rebuild from today's GIT (https://github.com/hydrogen-music/hydrogen/commit/2e236855f3cfcdcc33178dc16097a2da83734490), and I'm confirming that it is fixed now.

Added to https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7

I'm closing this issue now. Thanks for your celerity (again) !
