### ISSUE TITLE
master MUTE does not mute FX returns

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#470]
- select an FX for FX slot 1 (eg a delay)
- create a simple pattern with a snare 
- turn up de FX1 send of the snare and make sure the FX1 return is turned up
- now you should hear the original sound + the delay FX on the snare

- on the mixer hit the master mute button

expected : no sound at all
instead the original snare sound is muted, but the FX sound is still there

tested on latest git code

**Comment by trebmuh** [comment]
confirmed with git https://github.com/hydrogen-music/hydrogen/commit/3002477bfc6cb450b988f49d0a8a643a84e9530d on a Debian Jessie stable up-to-date

**Comment by trebmuh** [comment]
_(Hydrogen built from git master https://github.com/hydrogen-music/hydrogen/commit/bfc355ee5c3fa1a62f12d056427bc1a827764a61)_

Hi @thijz and @jeremyz : reopening this one since looking and retesting it, pressing MUTE on the mixer master track removes the delay effect but I can still hear the original snare sound.

**Comment by trebmuh** [comment]
Freshly rebuild from https://github.com/hydrogen-music/hydrogen/commit/5556c8dbc2a2c58f1441281739eab444273861d0 and it does work as expected
Merci @jeremyz !

**Comment by jeremyz** [comment]
tout le plaisir est pour moi @trebmuh !!
