### ISSUE TITLE
v0.9.7 only gets to splashscreen

### ISSUE THREAD

**Issue by nfn3** [hydrogen-music/hydrogen#500]
HI

I found Hydrogen yesterday, downloaded and installed it and it worked fine.

Today - it only gets to the splashscreen and then hangs. I rebooted my PC, same thing. Uninstalled and re-installed - same thing.

Running Win7.

Any ideas?

Cheers.

**Comment by thijz** [comment]
Sounds like h2 is waiting for the audio driver to become available.
Could it be that you were using a different audio driver during your first
test run? Or maybe you changed the audio driver settings?

Op 14 mei 2017 3:22 p.m. schreef "nfn3" <notifications@github.com>:

HI

I found Hydrogen yesterday, downloaded and installed it and it worked fine.

Today - it only gets to the splashscreen and then hangs. I rebooted my PC,
same thing. Uninstalled and re-installed - same thing.

Running Win7.

Any ideas?

Cheers.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hydrogen-music/hydrogen/issues/500>, or mute the thread

**Comment by nfn3** [comment]
Hi

Thanks for getting back to me.

I don't think the audio driver is the problem, otherwise wouldn't a re-install have worked, setting all options again? It didn't.

I managed to install v9.6, and that seems to work fine.

Just lacking in talent and inspiration now...

**Comment by mauser** [comment]
Hi! 

If you have problems with your configuration, it is always a good idea to delete/move your hydrogen configuration file. It should be located under C:\Users\username\.hydrogen and it will be named "hydrogen.conf". The sound driver settings are saved in that file.

Re-installing hydrogen does not necessarily wipe out that file.. This would be a problem because this file also includes your "preferences", like midi mappings.. You don't want to loose that data on a re-installation.
