### ISSUE TITLE
Very limited number of layers

### ISSUE THREAD

**Issue by dreng** [hydrogen-music/hydrogen#547]
Hi,
a couple of weeks ago I decided to go with Hydrogen because all of the big players lack Linux (namely LV2) support.

I was very exited when I read about Hydrogen's new round robin feature and I got even more exited when I found a huge drum kit with 127 velocity layers and up to 4 round robin layers for each Instrument here: https://smmdrums.wordpress.com. Unfortunately my intention to create a new very cool drum set for Hydrogen has been stopped when I noticed that only 16 layers can be used with Hydrogen. After compiling a version with a bigger MAX_LAYERS value I've been a little bit bugged about the wasted time and the need of installing a lot of development stuff I'd never need again. At least we can't expect anyone without any programmers experience to compile a custom version just for the sake of using a decent drum kit, can we?

Long story short: I decided to make some code changes which make it possible to set the max number of layers in the preferences dialog. It's not perfect so I'm not sure if it's worth a pull request. At lease it's a better solution than we have in the current release IMO.
1. One has to restart Hydrogen after changing the value in the preferences.
2. I left MAX_LAYERS in core/include/hydrogen/basics/instrument_component.h. Otherwise I had to define a vector and wasn't sure if dynamic arrays are a good idea in this case.
3. If the number of layers isn't a fixed value we need to take care while loading drum kits into Hydrogen. Otherwise it's possible that an instrument with e.g. 60 layers is being cut off at layer no. 16.

I'd be glad if someone could have a look into my fork and tell if it's worth to make a pull request: https://github.com/dreng/hydrogen/tree/max_layers_pref
Suggenstions are also welcome.

If the code will be commited I'll add a german translation.

**Comment by mauser** [comment]
Hi dreng! 

Thanks for your work! This topic has been brought up before, but up to now nobody really looked into the exact consequence of making MAX_LAYERS dynamic. 

About your three concerns: 

The necessity to restart Hydrogen is not a problem, since other settings are also requiring a restart. 

Using a dynamic array for the instrument components could be harmless if all additions / resize operations are not happening in the real-time code (driver callbacks). This has to be checked, but i would suppose that this can be done. 

About the third point: Maybe we should add a messagebox when such a kit is loaded, so that the user is warned that he might loose some layers if he saves that kit again.

**Comment by mauser** [comment]
And of course: A pull request is welcome :)

**Comment by dreng** [comment]
Hi Sebastian,
thanks for your reply. I've made some minor changes to my branch and added a pull request [](url)https://github.com/hydrogen-music/hydrogen/pull/550

**Comment by jeremyz** [comment]
there is still a warning to issue when maxLayers < # layers in the drumkit loaded

**Comment by theGreatWhiteShark** [comment]
> there is still a warning to issue when maxLayers < # layers in the drumkit loaded

There is already an ERRORLOG message taking care of this in both drumkit and song loading
