### ISSUE TITLE
Adding a pattern can be user-friendly improved.

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#584]
_[issue reported on linuxmao.org](http://linuxmao.org/forumthread84196) (in French)_ 

Hydrogen version *          : 0.97 & 1.0.0-beta1
Operating system + version  : LibraZiK-2 (Debian 9), but I'm pretty sure that is the case for every OS & version
Audio driver + version      : not useful here

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When loading a pattern, the pattern is added on the last place in the list, ie: after the last current pattern, which isn't user-friendly since it can gives the impression that nothing happened for a bunch of the usual workflows. The user needs then to scroll down on the patterns list to see the newly added pattern.

I think there are different ways of dealing with that from a GUI point of view and I'm sharing a few of those which are popping up in my head right now here:

- still adding the pattern below the last pattern in the list **but** "jumps" automatically to this one
- adding the pattern next to the current selected one
- adding the pattern in the middle of the actual view

Thought?

**Comment by pvint** [comment]
This is a good idea.

I like the first two options you suggested, but I think the third ("adding the pattern in the middle of the view") might seem a bit odd.
The best option to me would be "Add after the currently selected pattern", as it would seem intuitive to me, and it gives the user the option of choosing where it would go.

**Comment by trebmuh** [comment]
> The best option to me would be "Add after the currently selected pattern", as it would seem intuitive to me, and it gives the user the option of choosing where it would go.

I agree, totally.

**Comment by pvint** [comment]
I changed this so that the newly added pattern is inserted after the currently selected pattern (and is selected). Since this is a minor change I went ahead and merged it.

The only thing I don't like is that if you have the last pattern selected when you add, the view doesn't scroll to show the new pattern (it is still the active pattern though). Minor, but it would be nice to sort that out too.

**Comment by trebmuh** [comment]
Nice !
Tested from a fresh build, it works fine. Thanks @pvint !

**Comment by jeremyz** [comment]
@pvint, because of a very bad separation of GUI and lower level code in this project,
you missed the case of adding an empty pattern.

17be8d20 b3121d06 a6a70480 (and now we have undo for free !)

scroll the scrollbar to the newly added pattern still needs to be done

if only GUI code could use a properly desinged lower API instead of reimplementing over and over everywhere ;)

**Comment by pvint** [comment]
@jeremyz  Good catch, and thanks for fixing it up! Now it's done, and as an added bonus I learned something. :)

**Comment by mauser** [comment]
Hi! 
@trebmuh : Can this issue be closed?

**Comment by jeremyz** [comment]
Hello,
@mauser : scrolling to the newly added pattern still needs to be done.

**Comment by jeremyz** [comment]
Hahahaha, I know, I'm a bit anal sometimes ... and tired too.
