### ISSUE TITLE
sample editor : auto apply changes

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#60]
currently you need to apply the changes you have made to the sample editor parameters (in/out/loop points, loop mode ...)
this extra 'apply' step is easily forgotten and can be a bit annoying to do.

possible solution would be to remove the apply button and implement one of these 2 options :
- change the 'play' button behavior so it acts as a 'apply changes + play'
- apply the changes you make on the fly (that way you immediately see the changes you have made in the bottom window)

**Comment by theGreatWhiteShark** [comment]
> work on a temporary copy of the sample in the editing dialog with auto-apply, with the option of either applying the changes to the layer or to leave them (like Ok/Cancel)

I'm not quite sure since when but this behavior is already implemented. Any changes in the SampleEditor will be applied to the playback within the SampleEditor immediately. The "Apply Changes" button is only needed to use the changes in all Hydrogen too.

In addition, workflow is now even fast since pressing <kbd>Return</kbd> in any of the spin boxes without changing its value will trigger playback as well.
