### ISSUE TITLE
pattern editor : select copy/cut/move notes

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#62]
pattern editor :
- add option to select/cut/copy/move a selected region of notes, just like you can do on the song editor. This can save a lot of time if you are changing your pattern from 4bars to 8 for example.
  > not sure if the note settings (lead/lag, pan ...) can also be cut/moved to the new location ?

**Comment by oddtime** [comment]
Hi this has been finally implemented

**Comment by cme** [comment]
@oddtime:
> Hi this has been finally implemented

I hadn't even spotted this one! Thanks for trawling through the issues!  👍 

@wolftune :
> Ideally, the left/right function would be able to be very slightly moved, as in not-quantized, or quantized, according to the grid setting. So the whole selection would move over by steps the size of the grid.

Yes, this is what happens when moving with "Alt" held down. I hope that's discoverable enough, but I shall check it's documented. Thanks

**Comment by lrafa** [comment]
> Hi this has been finally implemented

I was very pleased to read this and went through the trouble of upgrading to Ubuntu 20.10 to then install Hydrogen-1.0.1... but the feature is not there... or at least it is not documented. Which version allows this?

This lack in feature is very strange, and it is the sole reason why I have to use rosegarden instead of hydrogen for drums.

**Comment by oddtime** [comment]
It will be in version 1.1 which should be released soon.
If you want to use right now you can build Hydrogen from the master branch in github
