### ISSUE TITLE
Crash when selecting Drumkits > Properties, and the song uses old GMKit

### ISSUE THREAD

**Issue by limerix** [hydrogen-music/hydrogen#654]
Hydrogen version *          : 1.0.0-beta1 [Mar 16 2018]
Operating system + version  : Windows 10
Audio driver + version      : not sure

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I updated to latest version and tried loading an old song. It opened but there was no sound.
When I selected menu Drumkits > Properties, it crashed.

 Assertion failed!
 MainForm.cpp, Line 2009
 Expression: drumkitInfo

The output from hydrogen.exe in msys shell shows this (just the interesting lines)

(E) Effects::getPluginList Error loading the library. (/jack-0.dll)
Etc. for many dlls, but the files exist.

(E) Filesystem::drumkit_path_search drumkit GMkit not found
Repeats sevral times, it makes sense as GMkit is not used anymore.

(E) Filesystem::check_permissions  is not a file
(E) Sample::load Unable to read
These two lines occur when I select the menu, and it crashes.

![2018-09-04_17h54_25](https://user-images.githubusercontent.com/12482684/45047522-901ab180-b079-11e8-8c57-ae281e039792.png)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mauser** [comment]
Hi! 

Thanks for the report, i can see in the code why this goes wrong. The dialog tries to access data which is accessible since the drumkit could not be found. Instead of quitting with a release assert, i've added a new meaningful error message for this case:

![grafik](https://user-images.githubusercontent.com/202461/45057622-60c66d80-b096-11e8-8c86-f42de35a8b1e.png)

The bug is fixed in the current master branch and will be present in the next release for windows.

**Comment by limerix** [comment]
Sounds perfect, many thanks for the quick fix!
