### ISSUE TITLE
Corrupted custom drumkit

### ISSUE THREAD

**Issue by Woffelson** [hydrogen-music/hydrogen#658]
Hydrogen version *          : 0.9.7
Operating system + version  : Ubuntu Studio 16.04 LTS

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

This issue is complicated to describe so I just try to explain what happened.

I had two similar custom drumkits. The latter was based on the former with less instruments. Since that latter limited version became useless for me, I decided to delete it. This however resulted that the original former drumkit didn't find any samples for its instrument layers despite them locating in the drumkit folder as usual.

I have a desktop computer where this drumkit still works. So, I tried to export it and import it as a new drumkit (after I had deleted the corrupted one). No matter if I rebooted the Hydrogen or my (laptop) computer, this exported drumkit also ended up being corrupted everytime. (I could try to rename it on the other computer before exporting, but that would create a new drumkit and if I would delete that as useless, I'd might have this same corruption issue on my desktop computer.)

The kit was originally created before 0.9.7 but if that's the issue at least exporting the kit as "0.9.7 or higher" doesn't fix that.

I hope there would be some workaround for this because for now the whole drumkit is unusable on my laptop computer no matter what I do. Only option would be to recreate it but it was a really big drumkit with many multilayers...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mauser** [comment]
Hi! 

Thanks for your report!

It seems that this is a very similiar issue to #622, but in this case, the "Release" property of one instrument has a float value:

  `<Release>4107.62</Release>`

This is a problem since our own schema validation expects an integer there and thinks that the whole xml is invalid. Because of that, Hydrogen thinks that the XML has been saved with an older version of hydrogen and is not able to load all of the layers of the drumkit. 

It seems that other ADSR properties, such as Decay and Attack, have the save problem. Hydrogen saves them as floats, but our XSD defines them be xsd::nonNegativeInteger. 

@jeremyz , do you have time for looking into this issue? Just ping me if not..

**Comment by mauser** [comment]
@Woffelson : A corrected version of your drumkit.xml is attached to this issue. If you copy it to your drumkit folder, i hope you will be able to work with that kit again.
[drumkit.zip](https://github.com/hydrogen-music/hydrogen/files/2408883/drumkit.zip)

**Comment by Woffelson** [comment]
Thank you, it works now! Hopefully the bug gets squashed as well.

**Comment by jeremyz** [comment]
my thoughts on ADSR:
- ADSR should be set using a visual gui based on the SampleEditor
- units of ADR should be [ms] not ticks
- ADSR::get_value( float step) is called with step=1 by default,
  this should be called with current time position is the sample
