### ISSUE TITLE
Playback track is affected by tempo changes

### ISSUE THREAD

**Issue by NihiliJay** [hydrogen-music/hydrogen#680]
Hydrogen version *          : Latest
Operating system + version  :  Windows 10
Audio driver + version      : 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Change playback track to ignore tempo changes.
After importing click/bed track as a wav file, tempo changes also shifts the playback track.

**Comment by theGreatWhiteShark** [comment]
Which audio driver do you use?

**Comment by NihiliJay** [comment]
Just the onboard Realtek HD
I have a somewhat dated computer Asus p6x58d-e

**Comment by theGreatWhiteShark** [comment]
In the drop-down menu at the very top of _Preferences > Audio System_ you can select different audio drivers Hydrogen can use to talk to your audio device. Do these jumps in the playback track occur using all of them?

By the way: Did I get you right that you import a click track to play along with Hydrogen and still use its internal audio engine to perform tempo changes? Why don't you use the the Metronome of Hydrogen instead of a click track?

**Comment by NihiliJay** [comment]
I've used guitar pro and tabbed out my songs including a click track line. Exported that as a wav. in hopes to create the drum tracks then bring that into a DAW to then properly record.
Many of the songs have varied tempo changes and all was working well till i noticed a glitch when the tempo changed. I finally realized that the tempo change seems to either skip the bed track or it speeds it up much like if you bumped a record player while its playing.
I'll try what you suggested but i've just finished re-installing my system with a SSD upgrade so give me a bit.

I appreciate the help.

**Comment by theGreatWhiteShark** [comment]
Hydrogen is written to work with external audio software synchronizing the playback of various programs, like the JACK server. If such an external software informs Hydrogen about a tempo change, the playback speed of will be altered and playback position will be relocated. E.g. you change the speed from 120bpm to 240bpm after one minute. Right before the tempo change 120 beats were passed and the "temporal position" is at one minute. After changing the speed the current position of 120 beats would correspond to a "temporal position" of half a minute. To avoid this problem, Hydrogen keeps an internal representation of the transport position and some logic in the audio engine to smooth out these tempo changes. But maybe something is implemented wrong concerning the playback track in the audio driver of yours. (I can't verify it since I'm no Windows user).

I would suggest you drop the click track and solely rely on Hydrogen's metronome. You can insert discrete tempo changes at the beginning of each pattern and thus the dynamics you wrote in GuitarPro. It might be a little hard at first but the skips can introduce small discrepancies between the original click track and the one you hear in Hydrogen, which could ultimately spoil your recording.

**Comment by elpescado** [comment]
> Which audio driver do you use?

AFAIR, on Windows there's only PortAudio.

**Comment by theGreatWhiteShark** [comment]
> AFAIR, on Windows there's only PortAudio.

I never tried it but official webpage [suggests](http://www.jackaudio.org/faq/jack_on_windows.html) the JACK server can also be run on Windows. As long as the API is still the same, I don't see why the JACK audio driver of Hydrogen should not run on Windows as well.

**Comment by elpescado** [comment]
You're right. It seems I was under impression that JACK is Linux-only.

**Comment by toraqi** [comment]
I have the same issue, I basically have to manually cut my playback track at every tempo change in order to use it. Does anyone know what causes this or how to fix it?

**Comment by theGreatWhiteShark** [comment]
Hydrogen does basically scale time when encountering a tempo change. What is required is another "time" that won't be affected and could be used for the playback track (and a couple of other things). 

I intend to rewrite/fix some issues with the Timeline and it's current implementation for an upcoming release and will try to cover this one too.

**Comment by theGreatWhiteShark** [comment]
Fixed with #1435
