### ISSUE TITLE
[FEATURE REQUEST] batch export drumloops from command-line/script

### ISSUE THREAD

**Issue by nathanaelmeister** [hydrogen-music/hydrogen#696]
Hydrogen version * : 0.9.7
Operating system + version : Debian GNU/Linux buster/sid
Audio driver + version : jackdmp version 1.9.12
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I use to export drum-loops to audio-files in many different tempos quite often,
which is quite annoying to do, since I have to change the tempo all the time and then export to a new file. If it was possible export audio from the command-line it would help quite a lot so something like this would be possible:

`hydrogen --export --tempo 96 my-beat.h2song` my-beat-96.flac`

**Comment by theGreatWhiteShark** [comment]
Since you are using Hydrogen with the JACK audio server, all ports etc have to be properly connected each time you would run such a command line command. The sound needs to propagate through all the clients (e.g. external LADSPA effects to alter the drum sound) and another JACK client has to capture the audio at the end of the connection path again and save it to disk. In addition, a more fine-grained control over all of Hydrogen's features via command line arguments would be required. This is a lot to do and most probably out of the scope of Hydrogen.

Instead I would recommend you to write a script which will
1. Create a JACK client and connects its ports to the end of the connection path
2. Moves the playback position to the beginning of the song
3. Sets a new tempo as timebase master using the JACK API
4. Starts playback via the JACK server and records all incoming audio
5. Stops playback at a predefined time
6. Repeats with 2. and a new tempo

You would need a language, which is able to write audio files (most are) and can use the JACK API. E.g. [C++](https://github.com/harryhaaren/openAudioProgrammingTutorials/blob/master/jackClient/jackClient.cpp), [Python](https://jackclient-python.readthedocs.io/en/0.4.5/) or [Lua](https://github.com/stetre/luajack). But there are many more available.

**Comment by elpescado** [comment]
It's possible to export sonv in command line via `h2cli` command and `-o` switch, eg.

`h2cli song.h2song -o song.wav`

Unfortunately, `h2cli` was broken some time ago, so that might not work.

It's not possible to specify tempo for export. If you want to script it, you might try use `sed`.

**Comment by mauser** [comment]
I'm closing this issue, since the problems seems to be solved.
