### ISSUE TITLE
BETA BUG: Horizontal scroll

### ISSUE THREAD

**Issue by esbatl** [hydrogen-music/hydrogen#746]
Hydrogen version *          : 1.0.0-beta1
Operating system + version  : Windows 10

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

So uhhhhhhhhh the pattern sequence area scrolls horizontally to the right whenever it reaches the second to last full pattern in the window, like [this](https://youtu.be/MYqlL75TyjQ). I also odn't seem to be able to simply scroll horizontally to play thru a different area of the song. Uhhhhhhhh, what do? :/

**Comment by theGreatWhiteShark** [comment]
Yeah, this one is annoying, isn't it?

But it is already fixed. The "only" thing you have to do is to switch to the most recent version of the application which means downloading the code from the master branch here on Github and compiliing/installing it yourself.

**Comment by esbatl** [comment]
Is there a way of compiling it that won't take up doesn't of gigs on my hard drive?

**Comment by theGreatWhiteShark** [comment]
Unfortunately, I have no idea about Windows operating system or how to build software using it. But would you mind creating a dedicated page in our Github wiki and describing all necessary steps for compilation in order to help other users as well?

A general remark: If the `hydrogen.exe` binary is way larger than expected (30MB on my system), you probably linked all dependencies statically. Setting your compiler options to dynamically shrinks the executable but might result in breaking the application when you update your system.
