### ISSUE TITLE
Youtube videos stop playing when using Hydrogen (0.9.6.1) on Linux Mint

### ISSUE THREAD

**Issue by bartvdg** [hydrogen-music/hydrogen#748]
Hydrogen version *          : 0.9.6.1
Operating system + version  : Linux Mint 18.3 Sylvia
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Youtube videos stop playing (loading mode?) when using Hydrogen (0.9.6.1) on Linux Mint 18.3.

**Comment by theGreatWhiteShark** [comment]
This is most probably a PulseAudio issue.

My guess is that Hydrogen uses JACK as audio driver, which is not running prior to the call and start up by Hydrogen.

I would recommend to start JACK before opening Hydrogen with QJackCtl and suspend PulseAudio with the `pasuspender` command since the latter tends to mess things up. Once JACK started both Youtube and Hydrogen should work just fine

**Comment by mauser** [comment]
Hi,

i'm closing this issue since at it does not seem to be an issue with Hydrogen and further information is lacking.
