### ISSUE TITLE
[Feat Req] Main Pitch control in instrument "General" panel

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#763]
A main pitch control knob in instrument "General" panel (acting on all the layers) may be useful,
e.g. for changing the tuning of a multi-layered tom.

**Comment by theGreatWhiteShark** [comment]
Yes, I second that. 

Could be placed right next to "random pitch" and called something like "pitch offset".

I would also help implementing it (since the GUI and core parts of this task are mostly orthogonal problems we could share ;) ) but there are some other features in H2 I want to implement first.

**Comment by oddtime** [comment]
Just one widget or Coarse + Fine?
I would choose a text entry instead of/in addition to the rotating widget.

**Comment by oddtime** [comment]
![instrumentTab_new2](https://user-images.githubusercontent.com/54219881/99243817-7cdf0100-2801-11eb-9423-c5a3db5abb45.png)

**Comment by theGreatWhiteShark** [comment]
> User should be able to click on the lcd display and enter the pitch offset as text

Hmm. But this would make its behavior inconsistent compared to the other LCD displays in Hydrogen. But in general I like the idea

**Comment by oddtime** [comment]
One only rotating widget may be not accurate enough for this, a text entry would solve this easily.
Personally I would applying the same behaviour to the other LCD as well.

**Comment by theGreatWhiteShark** [comment]
I don't see why LCD inputs are more precise than rotating widgets. For both you set the minimum and maximum possible value and the precision of the rotating widget can be adjusted in the code. Also I found its dynamic behavior (using both touchpad and mouse) quite good. Plus the particular value is displayed in a popup LCD display as soon as the value of the rotation widget gets changed.

On the other hand, adding a LCD display to every knob in Hydrogen would make the GUI even more dense and overloaded.

**Comment by oddtime** [comment]
For pitch shifting one only rotating widget is not sufficient for fine tuning ([-12,+12] with 0.01 precision), I suppose that this brought developers to use Coarse + Fine widgets in the layer editor. And still it's slower adjusting the value with the mouse if you want a given value.

> On the other hand, adding a LCD display to every knob in Hydrogen would make the GUI even more dense and overloaded.

I would not add a new LCD display to all the rotating widgets like Attack, Decay etc, there's non space.
A functional way would be text entry after double click on rotating widgets and the already present LCD display widgets.

**Comment by theGreatWhiteShark** [comment]
Ah, I see. Makes sense.

What about having a non-interactive LCD display next to three rotating widgets: pitch, fine, and random?

The problem with having a new widget type you can double click on is IMHO the inconsistency. Because this won't work with any other widget in Hydrogen, it is a somewhat hidden feature only known to people familiar with the code base or those reading the manual back to cover. If it, however, would be implemented for all widgets, this could be quite helpful.

**Comment by oddtime** [comment]
Ok

**Comment by oddtime** [comment]
Open Pull Req #1000
