### ISSUE TITLE
[Q] are exported songs in stereo?

### ISSUE THREAD

**Issue by Megver83** [hydrogen-music/hydrogen#805]
Just wondered if the imported song is in fact a stereo or mono track. I know that it's, in theory, stereo, but is it for real? Are the two mono tracks different from each other? I ask this because I analyzed a drums track in Ardour (with Calf Analyzer) and the signal was behaving like stereo but in some moments like mono (the signal was in the center)

If it's not 100% stereo, I would like to request it as a new feature for future versions, please

**Comment by elpescado** [comment]
Hydrogen exports songs as stereo track. But samples might be monophonic - that's the case with both included drum kits (GMRockKit and TR808EmulationKit). That means the only differences between left and right channels in exported song are because of panning.

![Zrzut ekranu 2020-02-29 o 16 47 43](https://user-images.githubusercontent.com/1619113/75610675-95907500-5b13-11ea-9372-2b1909e7c6e5.png)

**Comment by mauser** [comment]
@Megver83 : Are there any open questions or can we close this issue?

**Comment by Megver83** [comment]
> @Megver83 : Are there any open questions or can we close this issue?

No, my doubt is already answered. Closing
