### ISSUE TITLE
i18n update

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#833]
@mauser can you please refresh the translation files? I spotted a few untranslated strings in the beat2 GUI but the .po doesn't seems to includes those.

**Comment by mauser** [comment]
Do you mean running the updateTranslation Scripts? There are no changes to the .ts file, so all strings seem to be present there..

**Comment by trebmuh** [comment]
Thanks for that @mauser . That probably mean that the strings aren't marked as translatable in the source. I'll report precisely which are missing with screenshot on the coming days then.

**Comment by mauser** [comment]
@trebmuh : do you have any update on this issue?

**Comment by trebmuh** [comment]
Sorry, I forgot on that one. I'll try to do that later today.

**Comment by trebmuh** [comment]
Here we are:

![hydrog-i18n](https://user-images.githubusercontent.com/8705846/79080576-65ddab00-7d16-11ea-97ee-12c56e00120d.png)
![hydro-i18n-2](https://user-images.githubusercontent.com/8705846/79080605-a5a49280-7d16-11ea-9bb0-5946ae32f3e5.png)
![hydro-i18n-3](https://user-images.githubusercontent.com/8705846/79080579-6bd38c00-7d16-11ea-8ccf-3e897bc206b2.png)
![hydro-i18n-4](https://user-images.githubusercontent.com/8705846/79080580-6d9d4f80-7d16-11ea-88db-1070340a6684.png)
![hydro-i18n-5](https://user-images.githubusercontent.com/8705846/79080581-6ece7c80-7d16-11ea-8706-a8dfc33c9663.png)

**Comment by mauser** [comment]
Hi,

the problem has been caused by eda1cf5f2d5e30ac0e0bf0c30ffac13ed082fd45. In this commit, the ts files were renamed, for example from `hydrogen.fr.ts` to `hydrogen_fr.ts`. The updateTranslations script has not been updated in this commit, so it was generating translation updates to the wrong files. 

This issue should be fixed now, i've updated the script in the master branch. The properties (as shown above) are not translatable, since they come from a h2song file.

**Comment by trebmuh** [comment]
I've update the French translation in master, rebuild master and it looks fine here. I'll send a message to the translators on the -dev ML.
Thank you @mauser !
