### ISSUE TITLE
Created drumkit does not load instrument layers

### ISSUE THREAD

**Issue by RobinR1** [hydrogen-music/hydrogen#839]
Hydrogen version *          : 1.0.0-beta1
Operating system + version  :  openSUSE Leap 15.1
Audio driver + version      : ALSA

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I created a new drumkit with 10 instruments, all  with different layers and saved it.
But when I try to load it, or click-drag instruments from it into the current project the
layers and samples of the instruments are not loaded.
When I check the XML file, all looks sane and good.
No error messages are given.

Also tried loading the drumkit in 0.9.7, but with the same result.

Default drumkits and drumkits I previously created in 0.9.7 load correctly in 1.0.0-beta1

**Comment by RobinR1** [comment]
Please find the problematic drumkit here: https://drive.google.com/open?id=1ZFIyaCfXDv5DaDk0tUOOpRr6GZhHKS5j

**Comment by trebmuh** [comment]
@RobinR1 : can you try with [1.0.0-beta2](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta2)?

**Comment by RobinR1** [comment]
After a bit of struggling I managed to compile beta2 locally (the beta1 version I used came from https://build.opensuse.org/package/show/multimedia:apps/hydrogen and trying to adapt it there to beta2 resulted in a build that gives me '[main] Unknown exception X-(' when ran. Not sure why..).
My locally compiled version, fails to load the ALSA driver, but at least the gui works. 
But also here, when I load this drumkit, the layers are not loaded. So I assume the problem is still present in beta2.

**Comment by trebmuh** [comment]
OK, thanks for that. Let's see what the coding persons will tell you.

**Comment by mauser** [comment]
Hi! 

I will have a look into that issue, probably tomorrow. What version of Hydrogen have you used to create the drumkit which you have linked here? 1.0.0-beta2?

**Comment by RobinR1** [comment]
The drumkit was created using 1.0.0-beta1. The layers are not loaded when opened in 1.0.0-beta1, 0.9.7 and in 1.0.0-beta2 the layers are even removed from the drumkit.xml upon first start of hydrogen with the drumkit present in the user directory.

**Comment by mauser** [comment]
This is the same reason as in #658 : The drumkit.xml contains  <Release> nodes which have float values. This is a bug, since Hydrogen expects an integer there. This may happen in Hydrogen 1.0-beta1 and before. 

So if you load the file again, Hydrogen detects the drumkit file as invalid and tries to save the file again (to upgrade it). I will have to investigate further to see why the layers are getting lost (and didn't get lost in the prior versions).

To fix the problem, you have to manually edit the drumkit file and clean up all "Release" nodes so that they contain only integer values. See the attached file for an example, i'm not sure if i have preserved all values correctly from your original file.
[drumkit.zip](https://github.com/hydrogen-music/hydrogen/files/4482003/drumkit.zip)

**Comment by mauser** [comment]
Ok, i could trace the problem back to commit fa56cdd9b68ec0a0bf2de76abd492531962cc7cd. This means that 1.0-beta1 did not try to save the file again, which explains why you don't see that behavior in earlier versions. 

We will discuss if this saving is necessary or helpful in this case.

**Comment by mauser** [comment]
Hi,

i hope that i've fixed the problem now (fix is available in our master branch). Hydrogen now upgrades the files correctly. In addition, when upgrading files, it will keep the original file as a backup (drumkit.xml.bak).

I'm closing this issue now since the initial problems is fixed. Just re-open it if there are still any problems.
