### ISSUE TITLE
[ Feature Request ] Adding multiple bars (for playing the pattern) once

### ISSUE THREAD

**Issue by Porrumentzio** [hydrogen-music/hydrogen#891]
As far as I know, there's no way to add 28 bars of the same pattern if not touching each of those 28 bars.
It would be good to be able to add multiple bars selecting the number of bars you want and adding them all together.

![irudia](https://user-images.githubusercontent.com/61913683/83171290-2e845b80-a116-11ea-9d48-38cc2efefd2a.png)

**Comment by cme** [comment]
Similarly #866 , which I've implemented in #847 which is penciled in for 1.1.

The Song Editor's 'select' mode currently will clear all cells if you select and then hit the Delete key. There's probably a corresponding useful case that would involve filling a selection rather than deleting, but there's no "obvious" discoverable key for that.

It feels like there should be contextual menus in the Song Editor for useful operations.

But for the sake of a workaround for improving your workflow on *current* Hydrogen, if you want one, you can use Select mode to select a few active cells, and then Ctrl+drag them (Cmd+drag on macOS) to copy rather than just move them.

**Comment by Porrumentzio** [comment]
Thank you for the answer! I didn't see those #866 and #847 issues, but are exactly what I meant. I'll close this issue to clean-up the Opened Issue tag :)

Thanks for your advice about the current Hydrogen, that will be useful!
