### ISSUE TITLE
ui is too big

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#914]
Hydrogen version *          :1.0
Operating system + version  : windows 10
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

the ui is too big

![Annotation 2020-08-04 102926](https://user-images.githubusercontent.com/8137561/89312940-7d320280-d63d-11ea-8c09-ff7c433e6b70.jpg)

**Comment by cme** [comment]
Hi, can you tell us about your system, please? 

Is your monitor High-DPI and very small? Do you have Windows UI scaling turned on?

Your screenshot has a resolution of 144DPI which would be consistent with having hidpi emulation but user interface scaling set to 50%? 

On a straight win10 without hidpi or any scaling set, the user interface is as expected:

![Screenshot 2020-08-04 at 17 58 21](https://user-images.githubusercontent.com/768466/89322486-2c8dca00-d67c-11ea-8187-b42ccc032862.png)

**Comment by Reaper10** [comment]
dose this help?
![Annotation 2020-08-04 145017](https://user-images.githubusercontent.com/8137561/89338283-fa6f6e80-d661-11ea-831e-eab1c7512dae.jpg)

**Comment by cme** [comment]
Thank you. Yes, with that and some research I see what the problem is.

I guess 150% is the default that Windows picks for scaling given the size of your monitor. The issue is that by default Qt rounds the UI scaling factor to the nearest integer. At 150% scaling, that means it'll round it up to scale by 200%. Yuck.

If you try setting your desktop scale to 125% rather than 150%, Qt will select 100% scale for Hydrogen to use, which will be half the size.

That may be too small, and indeed it seems wrong to have to set the scaling of your entire desktop just for one application!

It's possible to get it to scale to match your UI size by going to:

  Windows Settings -> Edit environment variables for your account

Hit "New..." and enter the variable name

```QT_SCALE_FACTOR_ROUNDING_POLICY```

and give it the value:

```PassThrough```

or the value

```Floor```

to scale to 100% regardless of your Windows UI scaling factor.

**Comment by cme** [comment]
Fix is on master, pending release.
