### ISSUE TITLE
Tag 1.0.1 has no branch

### ISSUE THREAD

**Issue by tartina** [hydrogen-music/hydrogen#967]
Hydrogen version *          : 1.0.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Tag 1.0.1 is not contained in a branch, it's very difficult to find it.
Maybe it could be in a 1.0.x branch

**Comment by mauser** [comment]
Hi! 

Commit 4886dc95073ec60760df2d860e17446e9c59424c is tagged 1.0.1, which is currently the head of the branches "release/1.0" and "1.0.0". I don't see the problem here. And why is it difficult to find? If you want to browse all tags via Github, you can use https://github.com/hydrogen-music/hydrogen/tags.

**Comment by tartina** [comment]
Ok, tag 1.0.0 was masking branch 1.0.0 so I didn't see that.
Sorry for this Issue I will close ASAP.
